/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial

/-!
# Ideal sheaves generated by global sections

For a scheme `X` and an ideal `I` of its ring of global sections, Mathlib's
`AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop I` is the quasi-coherent ideal sheaf `I·𝒪_X`
generated by `I`. This file records how these ideal sheaves interact with morphisms of schemes.

## Main results

* `AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_le_ker_iff`: `I·𝒪_Y` is contained in the
  kernel of `f : X ⟶ Y` exactly when `f^*` kills `I`, that is, when `f` factors through the zero
  scheme of `I`;
* `AlgebraicGeometry.Scheme.Hom.ker_Spec_map`: the kernel of `Spec S ⟶ Spec R` is the ideal sheaf
  of the kernel of the ring map;
* `AlgebraicGeometry.Scheme.IdealSheafData.comap_ofIdealTop`: the inverse image ideal sheaf of
  `I·𝒪_Y` along `f : X ⟶ Y` is `f^*(I)·𝒪_X`, so the zero scheme of `I` pulls back to the zero
  scheme of `f^*(I)`;
* `AlgebraicGeometry.Scheme.Hom.ker_pullback_fst_Spec_map`: the base change of the closed
  immersion `Spec S ⟶ Spec R` along `f : X ⟶ Spec R` is the zero scheme of the ideal of `𝒪_X`
  generated by the pullback of the kernel of `R → S`.

The last statement is the scheme-theoretic form of the identity
`X ×_{Spec R} Spec (R ⧸ I) = V(I·𝒪_X)`, for instance for the fibres of a scheme over a local ring.
-/

public section

open CategoryTheory Limits AlgebraicGeometry TopologicalSpace

namespace TauCeti

universe u

variable {X Y : Scheme.{u}}

/-- The ideal sheaf generated by an ideal `I` of global sections of `Y` is contained in the kernel
of `f : X ⟶ Y` exactly when the pullback of every element of `I` vanishes on `X`. -/
theorem _root_.AlgebraicGeometry.Scheme.IdealSheafData.ofIdealTop_le_ker_iff (f : X ⟶ Y)
    (I : Ideal Γ(Y, ⊤)) :
    Scheme.IdealSheafData.ofIdealTop I ≤ f.ker ↔ I ≤ RingHom.ker f.appTop.hom := by
  rw [Scheme.Hom.ker, Scheme.IdealSheafData.le_ofIdeals_iff]
  constructor
  · intro h s hs
    rw [RingHom.mem_ker]
    -- A global section vanishes once it vanishes on the preimages of the affine opens of `Y`.
    fapply TopCat.Sheaf.eq_of_locally_eq' X.sheaf (fun U : Y.affineOpens ↦ f ⁻¹ᵁ U.1) ⊤
      (fun _ ↦ homOfLE le_top)
    · intro x _
      have hx : f.base x ∈ (⊤ : Y.Opens) := trivial
      rw [← iSup_affineOpens_eq_top Y, Opens.mem_iSup] at hx
      obtain ⟨U, hU⟩ := hx
      exact Opens.mem_iSup.mpr ⟨U, hU⟩
    · intro U
      have hU := h U (Ideal.mem_map_of_mem (Y.presheaf.map (homOfLE le_top).op).hom hs)
      rw [RingHom.mem_ker, ← CommRingCat.comp_apply, f.naturality, CommRingCat.comp_apply] at hU
      -- `hU` restricts along `f ⁻¹ᵁ U ≤ f ⁻¹ᵁ ⊤`, the goal along `f ⁻¹ᵁ U ≤ ⊤`; the two opens
      -- `f ⁻¹ᵁ ⊤` and `⊤` are definitionally equal, as in the type of `Scheme.Hom.appTop`.
      exact hU.trans (map_zero _).symm
  · intro h U
    rw [Scheme.IdealSheafData.ofIdealTop_ideal, Ideal.map_le_iff_le_comap]
    refine h.trans fun s hs ↦ ?_
    have hs' : f.app ⊤ s = 0 := hs
    rw [Ideal.mem_comap, RingHom.mem_ker, ← CommRingCat.comp_apply, f.naturality,
      CommRingCat.comp_apply, hs', map_zero]

/-- The kernel of the morphism `Spec S ⟶ Spec R` induced by a ring map `R ⟶ S` is the ideal sheaf
of the kernel of the ring map, read in the global sections of `Spec R`. -/
theorem _root_.AlgebraicGeometry.Scheme.Hom.ker_Spec_map {R S : CommRingCat.{u}} (φ : R ⟶ S) :
    (Spec.map φ).ker =
      Scheme.IdealSheafData.ofIdealTop ((RingHom.ker φ.hom).map (Scheme.ΓSpecIso R).inv.hom) := by
  rw [Scheme.ker_of_isAffine]
  congr 1
  have h : (Spec.map φ).appTop = (Scheme.ΓSpecIso R).hom ≫ φ ≫ (Scheme.ΓSpecIso S).inv := by
    rw [← Scheme.ΓSpecIso_naturality_assoc, Iso.hom_inv_id, Category.comp_id]
  rw [h, CommRingCat.hom_comp, CommRingCat.hom_comp, RingHom.comp_assoc,
    RingHom.ker_comp_of_injective _ (ConcreteCategory.bijective_of_isIso (Scheme.ΓSpecIso S).inv).1,
    ← RingHom.comap_ker]
  -- The ring equivalence underlying `ΓSpecIso R` has `inv.hom` and `hom.hom` as its two maps.
  exact (Ideal.map_comap_of_equiv (Scheme.ΓSpecIso R).symm.commRingCatIsoToRingEquiv).symm

/-- **Inverse image of the ideal sheaf generated by global sections.** The inverse image along
`f : X ⟶ Y` of the ideal sheaf generated by an ideal `I` of global sections of `Y` is the ideal
sheaf generated by the pullbacks of the elements of `I`: the zero scheme of `I` pulls back to the
zero scheme of `f^*(I)`. -/
@[simp]
theorem _root_.AlgebraicGeometry.Scheme.IdealSheafData.comap_ofIdealTop (I : Ideal Γ(Y, ⊤))
    (f : X ⟶ Y) :
    (Scheme.IdealSheafData.ofIdealTop I).comap f =
      Scheme.IdealSheafData.ofIdealTop (I.map f.appTop.hom) := by
  set J := Scheme.IdealSheafData.ofIdealTop I with hJ
  set K := Scheme.IdealSheafData.ofIdealTop (I.map f.appTop.hom) with hK
  have hI : I ≤ RingHom.ker J.subschemeι.appTop.hom :=
    (Scheme.IdealSheafData.ofIdealTop_le_ker_iff _ _).mp J.ker_subschemeι.ge
  refine le_antisymm ?_ ?_
  · -- `K.subschemeι ≫ f` kills `I`, so it factors through the zero scheme `J.subscheme` of `I` and
    -- hence through the pullback of that zero scheme along `f`.
    have hK' : J.subschemeι.ker ≤ (K.subschemeι ≫ f).ker := by
      rw [Scheme.IdealSheafData.ker_subschemeι, Scheme.IdealSheafData.ofIdealTop_le_ker_iff,
        Scheme.Hom.comp_appTop, CommRingCat.hom_comp, ← RingHom.comap_ker,
        ← Ideal.map_le_iff_le_comap]
      exact (Scheme.IdealSheafData.ofIdealTop_le_ker_iff _ _).mp K.ker_subschemeι.ge
    have hlift : pullback.lift K.subschemeι (IsClosedImmersion.lift _ _ hK')
        (IsClosedImmersion.lift_fac _ _ hK').symm ≫ pullback.fst f J.subschemeι = K.subschemeι :=
      pullback.lift_fst _ _ _
    calc (pullback.fst f J.subschemeι).ker
        ≤ (pullback.lift K.subschemeι (IsClosedImmersion.lift _ _ hK')
            (IsClosedImmersion.lift_fac _ _ hK').symm ≫ pullback.fst f J.subschemeι).ker :=
          Scheme.Hom.le_ker_comp _ _
      _ = K := by rw [hlift, Scheme.IdealSheafData.ker_subschemeι]
  · -- The pullback of the zero scheme of `I` lies in the zero scheme of `f^*(I)`.
    rw [Scheme.IdealSheafData.comap, Scheme.IdealSheafData.ofIdealTop_le_ker_iff,
      Ideal.map_le_iff_le_comap, RingHom.comap_ker, ← CommRingCat.hom_comp,
      ← Scheme.Hom.comp_appTop, pullback.condition, Scheme.Hom.comp_appTop, CommRingCat.hom_comp,
      ← RingHom.comap_ker]
    exact hI.trans (Ideal.ker_le_comap _)

/-- **Base change of a closed subscheme of an affine scheme.** For a ring map `R ⟶ S` whose
induced morphism `Spec S ⟶ Spec R` is a closed immersion, for instance a surjective ring map, the
base change of this closed immersion along `f : X ⟶ Spec R` is the zero scheme of the ideal of
`𝒪_X` generated by the pullback of the kernel of `R ⟶ S`. -/
theorem _root_.AlgebraicGeometry.Scheme.Hom.ker_pullback_fst_Spec_map {R S : CommRingCat.{u}}
    (φ : R ⟶ S) [IsClosedImmersion (Spec.map φ)] (f : X ⟶ Spec R) :
    (pullback.fst f (Spec.map φ)).ker =
      Scheme.IdealSheafData.ofIdealTop
        ((RingHom.ker φ.hom).map ((Scheme.ΓSpecIso R).inv ≫ f.appTop).hom) := by
  rw [Scheme.IdealSheafData.ker_fst_of_isClosedImmersion, Scheme.Hom.ker_Spec_map,
    Scheme.IdealSheafData.comap_ofIdealTop, Ideal.map_map, CommRingCat.hom_comp]

end TauCeti
