/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.Combinatorics.DenseGraphLimits.GraphonSpace.HomDensity.Basic
public import Mathlib.MeasureTheory.Integral.BoundedContinuousFunction
public import Mathlib.Topology.ContinuousMap.Bounded.Star

/-!
# The algebra of homomorphism densities on graphon space

The homomorphism densities `t(F, ·)` of finite graphs `F` on `Fin n`, viewed as bounded continuous
functions on a graphon space, generate a unital star subalgebra `homDensityAlgebra` of
`GraphonSpace Ω μ →ᵇ ℝ`. This algebra is very rigid: the product of two homomorphism densities is
the homomorphism density of the disjoint union, and the edgeless graph on no vertices has density
`1`, so the generating family is already a multiplicative monoid and the algebra it generates is
nothing more than its linear span (`mem_homDensityAlgebra_iff_mem_span`).

Two consequences make the algebra the right coordinate system for measures on graphon space.
First, the integrals of its elements against a finite measure are determined by the *moments*
`∫ t(F, ·) dP` alone (`integral_eq_of_mem_homDensityAlgebra`). Second, the algebra
separates points exactly when the homomorphism densities do
(`homDensityAlgebra_separatesPoints_iff`). Together with the separation of finite measures by a
point-separating star subalgebra of bounded continuous functions on a Polish space
(`MeasureTheory.ext_of_forall_mem_subalgebra_integral_eq_of_polish`), these reduce the uniqueness of
the mixing measure in the Diaconis–Janson graphon-mixture representation to the separation of
graphon classes by their homomorphism densities.

## Main definitions

* `TauCeti.DenseGraphLimits.homDensityAlgebra` — the star subalgebra of bounded continuous
  functions on graphon space generated by the homomorphism densities of finite graphs.

## Main results

* `TauCeti.DenseGraphLimits.mem_homDensityAlgebra_iff_mem_span` — the algebra is the linear span of
  the homomorphism densities;
* `TauCeti.DenseGraphLimits.integral_eq_of_mem_homDensityAlgebra` — two finite
  measures with the same homomorphism-density moments integrate every element of the algebra
  alike;
* `TauCeti.DenseGraphLimits.homDensityAlgebra_separatesPoints_iff` — the algebra separates points
  iff the homomorphism densities do.

## References

* P. Diaconis, S. Janson, *Graph limits and exchangeable random graphs*, Rend. Mat. Appl. (7) 28
  (2008), 33--61, Section 5.
* L. Lovász, *Large Networks and Graph Limits*, AMS Colloquium Publications 60 (2012),
  Section 11.3.
-/

public section

noncomputable section

open MeasureTheory BoundedContinuousFunction

namespace TauCeti

namespace DenseGraphLimits

variable {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]

/-- **The algebra of homomorphism densities.** The star subalgebra of bounded continuous functions
on graphon space generated by the homomorphism densities of the finite graphs on `Fin n`, `n : ℕ`.
The star operation on real-valued functions is trivial, so this is the unital algebra generated by
the `homDensityBCF F`. -/
def homDensityAlgebra : StarSubalgebra ℝ (GraphonSpace Ω μ →ᵇ ℝ) where
  toSubalgebra := Algebra.adjoin ℝ
    {g | ∃ (n : ℕ) (F : SimpleGraph (Fin n)) (_ : DecidableRel F.Adj), homDensityBCF F = g}
  star_mem' {g} hg := by
    rwa [show star g = g from ext fun x => star_trivial _]

/-- Each generating homomorphism density belongs to the algebra it generates. -/
@[simp]
theorem homDensityBCF_mem_homDensityAlgebra {n : ℕ} (F : SimpleGraph (Fin n))
    [DecidableRel F.Adj] : homDensityBCF (μ := μ) F ∈ homDensityAlgebra :=
  Algebra.subset_adjoin ⟨n, F, ‹_›, rfl⟩

/-- **The algebra is the span.** Since the homomorphism densities are closed under products
(disjoint unions) and contain the constant `1` (the empty graph), the algebra they generate is their
linear span. -/
theorem mem_homDensityAlgebra_iff_mem_span {g : GraphonSpace Ω μ →ᵇ ℝ} :
    g ∈ homDensityAlgebra ↔ g ∈ Submodule.span ℝ
      {g | ∃ (n : ℕ) (F : SimpleGraph (Fin n)) (_ : DecidableRel F.Adj), homDensityBCF F = g} := by
  classical
  rw [← StarSubalgebra.mem_toSubalgebra, ← Subalgebra.mem_toSubmodule, homDensityAlgebra,
    Algebra.adjoin_eq_span_of_subset]
  intro g hg
  refine Submodule.subset_span ?_
  induction hg using Submonoid.closure_induction with
  | mem g hg => exact hg
  | one => exact ⟨0, ⊥, inferInstance, homDensityBCF_bot⟩
  | mul g₁ g₂ _ _ h₁ h₂ =>
    obtain ⟨n₁, F₁, _, rfl⟩ := h₁
    obtain ⟨n₂, F₂, _, rfl⟩ := h₂
    exact ⟨n₁ + n₂, (F₁ ⊕g F₂).map finSumFinEquiv.toEmbedding, inferInstance, by
      rw [homDensityBCF_map_embedding, homDensityBCF_sum]⟩

/-- **Moments determine the integrals over the algebra.** Two finite measures on graphon space with
the same average of every homomorphism density integrate every element of `homDensityAlgebra`
alike. -/
theorem integral_eq_of_mem_homDensityAlgebra {P Q : Measure (GraphonSpace Ω μ)}
    [IsFiniteMeasure P] [IsFiniteMeasure Q]
    (h : ∀ (n : ℕ) (F : SimpleGraph (Fin n)) [DecidableRel F.Adj],
      ∫ x, homDensityOnSpace F x ∂P = ∫ x, homDensityOnSpace F x ∂Q)
    {g : GraphonSpace Ω μ →ᵇ ℝ} (hg : g ∈ homDensityAlgebra) : ∫ x, g x ∂P = ∫ x, g x ∂Q := by
  rw [mem_homDensityAlgebra_iff_mem_span] at hg
  induction hg using Submodule.span_induction with
  | mem g hg =>
    obtain ⟨n, F, _, rfl⟩ := hg
    simpa using h n F
  | zero => simp
  | add f g _ _ hf hg =>
    simp only [coe_add, Pi.add_apply]
    rw [integral_add (f.integrable P) (g.integrable P), integral_add (f.integrable Q)
      (g.integrable Q), hf, hg]
  | smul a f _ hf =>
    simp only [coe_smul]
    rw [integral_smul, integral_smul, hf]

/-- Two points of graphon space with the same homomorphism densities are not distinguished by any
element of `homDensityAlgebra`. -/
theorem apply_eq_of_mem_homDensityAlgebra {x y : GraphonSpace Ω μ}
    (h : ∀ (n : ℕ) (F : SimpleGraph (Fin n)) [DecidableRel F.Adj],
      homDensityOnSpace F x = homDensityOnSpace F y)
    {g : GraphonSpace Ω μ →ᵇ ℝ} (hg : g ∈ homDensityAlgebra) : g x = g y := by
  rw [mem_homDensityAlgebra_iff_mem_span] at hg
  induction hg using Submodule.span_induction with
  | mem g hg =>
    obtain ⟨n, F, _, rfl⟩ := hg
    simpa using h n F
  | zero => simp
  | add f g _ _ hf hg => simp [hf, hg]
  | smul a f _ hf => simp [hf]

/-- **Separation of points.** The algebra of homomorphism densities, viewed inside `C(_, ℝ)`,
separates the points of graphon space iff the homomorphism densities themselves do. -/
theorem homDensityAlgebra_separatesPoints_iff :
    ((homDensityAlgebra (Ω := Ω) (μ := μ)).map (toContinuousMapStarₐ ℝ)).SeparatesPoints ↔
      ∀ x y : GraphonSpace Ω μ, (∀ (n : ℕ) (F : SimpleGraph (Fin n)) [DecidableRel F.Adj],
        homDensityOnSpace F x = homDensityOnSpace F y) → x = y := by
  constructor
  · intro hsep x y hxy
    by_contra hne
    obtain ⟨_, ⟨_, hg, rfl⟩, hgxy⟩ := hsep hne
    rw [SetLike.mem_coe, StarSubalgebra.mem_toSubalgebra, StarSubalgebra.mem_map] at hg
    obtain ⟨g, hg, rfl⟩ := hg
    exact hgxy (apply_eq_of_mem_homDensityAlgebra hxy hg)
  · intro hinj x y hne
    by_contra! h
    refine hne (hinj x y fun n F _ => ?_)
    simpa using h _ ⟨_, StarSubalgebra.mem_map.2 ⟨_, homDensityBCF_mem_homDensityAlgebra F, rfl⟩,
      rfl⟩

end DenseGraphLimits

end TauCeti
