/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.Fibers
public import TauCeti.AlgebraicGeometry.IdealSheaf.OfIdealTop

/-!
# The special fibre as the zero scheme of the maximal ideal

Let `X → Spec R` be a scheme over a local ring `R` with maximal ideal `𝔪`. Its special fibre is the
base change `X ×_{Spec R} Spec (R ⧸ 𝔪)`, a closed subscheme of `X`. This file identifies that closed
subscheme: its ideal sheaf is the quasi-coherent ideal sheaf `𝔪·𝒪_X` generated by the pullbacks of
the elements of `𝔪`. When `𝔪 = (π)` is principal, for instance when `R` is a discrete valuation
ring and `π` a uniformizer, the special fibre is therefore the zero scheme `V(π)` of the single
global function `π` pulled back to `X`.

For a discrete valuation ring, this is the scheme-theoretic statement that the special fibre `X_s`
is the effective Cartier divisor `div_X(π)`: the Weil divisor of `π` is supported on the components
of `X_s` with their multiplicities (`TauCeti.AlgebraicGeometry.SpecialFiber.Components`), and the
closed subscheme cut out by the local equation `π` is `X_s` itself.

## Main results

* `TauCeti.ker_specialFiberι`: the ideal sheaf of the special fibre is `𝔪·𝒪_X`;
* `TauCeti.ker_specialFiberι_eq_ofIdealTop_span`: when `𝔪 = (π)`, it is the ideal sheaf generated
  by the pullback of `π`;
* `TauCeti.specialFiberIsoSubscheme`: the special fibre is isomorphic over `X` to the zero scheme
  of `𝔪·𝒪_X`, and `TauCeti.isPullback_subschemeι_specialFiber` records the resulting pullback
  square.

## References

* [The Stacks Project, Section 55.9](https://stacks.math.columbia.edu/tag/0C9U), the special fibre
  of a regular model as the divisor of a uniformizer.
-/

public section

noncomputable section

open CategoryTheory Limits AlgebraicGeometry IsLocalRing

namespace TauCeti

universe u

variable (R : Type u) [CommRing R] [IsLocalRing R] {X : Scheme.{u}} (toBase : X ⟶ Spec (.of R))

/-- **The special fibre is cut out by the maximal ideal.** The ideal sheaf of the special fibre of
a scheme over a local ring is the ideal sheaf `𝔪·𝒪_X` generated by the pullbacks of the elements of
the maximal ideal `𝔪` of the base. -/
theorem ker_specialFiberι :
    (specialFiberι R toBase).ker =
      Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map ((Scheme.ΓSpecIso (.of R)).inv ≫ toBase.appTop).hom) := by
  have := isClosedImmersion_Spec_map_residue R
  rw [specialFiberι, Scheme.Hom.ker_pullback_fst_Spec_map, CommRingCat.hom_ofHom,
    ResidueField.algebraMap_eq, ker_residue]

variable {R}

/-- **The special fibre is the zero scheme of a uniformizer.** If the maximal ideal of the base is
generated by `π`, the ideal sheaf of the special fibre is generated by the pullback of `π`: the
special fibre is the zero scheme `V(π)` of the pullback of `π` to the total space. -/
theorem ker_specialFiberι_eq_ofIdealTop_span {π : R} (hπ : maximalIdeal R = Ideal.span {π}) :
    (specialFiberι R toBase).ker =
      Scheme.IdealSheafData.ofIdealTop
        (Ideal.span {toBase.appTop ((Scheme.ΓSpecIso (.of R)).inv π)}) := by
  rw [ker_specialFiberι, hπ, Ideal.map_span, Set.image_singleton, CommRingCat.hom_comp,
    RingHom.comp_apply]

variable (R)

/-- The special fibre of a scheme over a local ring is isomorphic, as a closed subscheme of the
total space, to the zero scheme of the ideal sheaf `𝔪·𝒪_X` generated by the maximal ideal of the
base. -/
noncomputable def specialFiberIsoSubscheme :
    (specialFiber R toBase).left ≅
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map ((Scheme.ΓSpecIso (.of R)).inv ≫ toBase.appTop).hom)).subscheme :=
  haveI := isClosedImmersion_specialFiberι R toBase
  have h := (Scheme.IdealSheafData.ker_subschemeι _).trans (ker_specialFiberι R toBase).symm
  haveI := IsClosedImmersion.isIso_lift _ (specialFiberι R toBase) h
  asIso (IsClosedImmersion.lift _ (specialFiberι R toBase) h.le)

/-- The identification of the special fibre with the zero scheme of `𝔪·𝒪_X` is compatible with the
inclusions into the total space. -/
@[reassoc (attr := simp)]
lemma specialFiberIsoSubscheme_hom_subschemeι :
    (specialFiberIsoSubscheme R toBase).hom ≫
        (Scheme.IdealSheafData.ofIdealTop
          ((maximalIdeal R).map ((Scheme.ΓSpecIso (.of R)).inv ≫ toBase.appTop).hom)).subschemeι =
      specialFiberι R toBase :=
  IsClosedImmersion.lift_fac _ _ _

/-- The inverse identification of the zero scheme of `𝔪·𝒪_X` with the special fibre is compatible
with the inclusions into the total space. -/
@[reassoc (attr := simp)]
lemma specialFiberIsoSubscheme_inv_specialFiberι :
    (specialFiberIsoSubscheme R toBase).inv ≫ specialFiberι R toBase =
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map ((Scheme.ΓSpecIso (.of R)).inv ≫ toBase.appTop).hom)).subschemeι := by
  rw [Iso.inv_comp_eq, specialFiberIsoSubscheme_hom_subschemeι]

/-- The zero scheme of `𝔪·𝒪_X`, with its inclusion into the total space and its induced morphism
to the spectrum of the residue field, is a pullback of `X → Spec R` and `Spec (R ⧸ 𝔪) → Spec R`:
it is the special fibre. -/
theorem isPullback_subschemeι_specialFiber :
    IsPullback
      (Scheme.IdealSheafData.ofIdealTop
        ((maximalIdeal R).map ((Scheme.ΓSpecIso (.of R)).inv ≫ toBase.appTop).hom)).subschemeι
      ((specialFiberIsoSubscheme R toBase).inv ≫ (specialFiber R toBase).hom)
      toBase (Spec.map (CommRingCat.ofHom (algebraMap R (ResidueField R)))) :=
  (isPullback_specialFiber R toBase).of_iso (specialFiberIsoSubscheme R toBase) (Iso.refl _)
    (Iso.refl _) (Iso.refl _)
    ((Category.comp_id _).trans (specialFiberIsoSubscheme_hom_subschemeι R toBase).symm)
    (by rw [Iso.refl_hom, Category.comp_id, Iso.hom_inv_id_assoc]) (by simp) (by simp)

end TauCeti
