/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part00
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part01
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part02
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part03
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part04
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part05
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part06
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part07
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part08
public import TauCeti.GroupTheory.SpecificGroups.CFSG.BasicProperties.Mathieu.M11CosetCertificate.RelationSoundness.Part09

/-! All scan words are closed in the exact M11 presentation group. -/

public section

namespace TauCeti.Sporadic.Mathieu.M11CosetCertificate.RelationSoundness

open Relations

@[expose]
def closedRelators : List (List (Fin 4)) :=
  scanBlock0 ++
    scanBlock1 ++
    scanBlock2 ++
    scanBlock3 ++
    scanBlock4 ++
    scanBlock5 ++
    scanBlock6 ++
    scanBlock7 ++
    scanBlock8 ++
    scanBlock9 ++
    scanBlock10 ++
    scanBlock11 ++
    scanBlock12 ++
    scanBlock13 ++
    scanBlock14 ++
    scanBlock15 ++
    scanBlock16 ++
    scanBlock17 ++
    scanBlock18 ++
    scanBlock19 ++
    scanBlock20 ++
    scanBlock21 ++
    scanBlock22 ++
    scanBlock23 ++
    scanBlock24 ++
    scanBlock25 ++
    scanBlock26 ++
    scanBlock27 ++
    scanBlock28 ++
    scanBlock29 ++
    scanBlock30 ++
    scanBlock31 ++
    scanBlock32 ++
    scanBlock33 ++
    scanBlock34 ++
    scanBlock35 ++
    scanBlock36 ++
    scanBlock37 ++
    scanBlock38 ++
    scanBlock39

theorem closedRelators_eq_one : ∀ w ∈ closedRelators,
    (w.map letterValue).prod = 1 := by
  intro w hw
  simp only [closedRelators, List.mem_append, or_assoc] at hw
  rcases hw with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
    | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
  · exact scanBlock0_eq_one w h
  · exact scanBlock1_eq_one w h
  · exact scanBlock2_eq_one w h
  · exact scanBlock3_eq_one w h
  · exact scanBlock4_eq_one w h
  · exact scanBlock5_eq_one w h
  · exact scanBlock6_eq_one w h
  · exact scanBlock7_eq_one w h
  · exact scanBlock8_eq_one w h
  · exact scanBlock9_eq_one w h
  · exact scanBlock10_eq_one w h
  · exact scanBlock11_eq_one w h
  · exact scanBlock12_eq_one w h
  · exact scanBlock13_eq_one w h
  · exact scanBlock14_eq_one w h
  · exact scanBlock15_eq_one w h
  · exact scanBlock16_eq_one w h
  · exact scanBlock17_eq_one w h
  · exact scanBlock18_eq_one w h
  · exact scanBlock19_eq_one w h
  · exact scanBlock20_eq_one w h
  · exact scanBlock21_eq_one w h
  · exact scanBlock22_eq_one w h
  · exact scanBlock23_eq_one w h
  · exact scanBlock24_eq_one w h
  · exact scanBlock25_eq_one w h
  · exact scanBlock26_eq_one w h
  · exact scanBlock27_eq_one w h
  · exact scanBlock28_eq_one w h
  · exact scanBlock29_eq_one w h
  · exact scanBlock30_eq_one w h
  · exact scanBlock31_eq_one w h
  · exact scanBlock32_eq_one w h
  · exact scanBlock33_eq_one w h
  · exact scanBlock34_eq_one w h
  · exact scanBlock35_eq_one w h
  · exact scanBlock36_eq_one w h
  · exact scanBlock37_eq_one w h
  · exact scanBlock38_eq_one w h
  · exact scanBlock39_eq_one w h

theorem relators_eq_closedRelators : M11CosetCertificate.relators = closedRelators := by
  decide +kernel

/-- Every relator consumed by the table checker holds in the exact group. -/
theorem relators_eq_one : ∀ w ∈ M11CosetCertificate.relators,
    (w.map letterValue).prod = 1 := by
  rw [relators_eq_closedRelators]
  exact closedRelators_eq_one

/-- The checker subgroup words lie in the cyclic subgroup generated by `x`. -/
theorem subgroupWords_mem : ∀ w ∈ M11CosetCertificate.subgroupWords,
    (w.map letterValue).prod ∈ Subgroup.zpowers x :=
  subgroup_words_mem

end TauCeti.Sporadic.Mathieu.M11CosetCertificate.RelationSoundness
