/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.EuclideanDomain.Int
public import Mathlib.Algebra.Module.Injective
public import Mathlib.Data.Int.GCD
public import Mathlib.Data.ZMod.Basic
public import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# `ℤ/nℤ` is an injective module over itself

For `n ≠ 0` the ring `ℤ/nℤ` is self-injective: every `ℤ/nℤ`-linear map from an ideal of `ℤ/nℤ`
to `ℤ/nℤ` extends to the whole ring, which is Baer's criterion (`Module.Baer`) for the module
`ℤ/nℤ` over itself. Consequently `Hom(-, ℤ/nℤ)` is exact on the abelian groups killed by `n`, which
is what makes the dual `M ↦ Hom(M, ℤ/nℤ)` of a finite abelian group of exponent dividing `n` behave
like the dual of a vector space; the duality statements for the finite `ℤ/pⁱ[G]`-modules of a
profinite group rest on this.

The proof is the usual one. An ideal of `ℤ/nℤ` is generated by one element `d`, and a linear map
on it is determined by the image `x` of `d`, which is killed by every `r` killing `d`. In `ℤ/nℤ`
that forces `d ∣ x` (`ZMod.dvd_of_forall_mul_eq_zero`): if `g = gcd(d, n)`, then `n/g` kills `d`,
hence `x`, so `g` divides `x`, and `g` is a multiple of `d` by Bézout. Writing `x = d y`, the map
`r ↦ r y` is the required extension. The hypothesis `n ≠ 0` is necessary: `ℤ` is not injective
over itself, since the map `2ℤ → ℤ`, `2 ↦ 1`, does not extend.

## Main results

* `ZMod.dvd_of_forall_mul_eq_zero`: in `ℤ/nℤ`, if every `r` with `r d = 0` has `r x = 0`, then
  `d ∣ x`.
* `Module.Baer.zmod_self`: `ℤ/nℤ` satisfies Baer's criterion over itself, for `n ≠ 0`.
-/

public section

namespace ZMod

variable {n : ℕ} [NeZero n]

/-- **Divisibility in `ℤ/nℤ` from annihilators.** If every `r : ZMod n` with `r * d = 0` also has
`r * x = 0`, then `d ∣ x`. With `g = gcd(d, n)`, the element `n / g` kills `d`, hence `x`, so `g`
divides `x`; and `g` is a multiple of `d` in `ZMod n` by Bézout. -/
theorem dvd_of_forall_mul_eq_zero {d x : ZMod n}
    (h : ∀ r : ZMod n, r * d = 0 → r * x = 0) : d ∣ x := by
  set g := Nat.gcd d.val n with hg
  obtain ⟨m, hm⟩ : g ∣ n := Nat.gcd_dvd_right _ _
  have hmpos : 0 < m := Nat.pos_of_ne_zero fun h0 => NeZero.ne n (by rw [hm, h0, mul_zero])
  -- `m = n / g` kills `d`
  have hmd : (m : ZMod n) * d = 0 := by
    obtain ⟨k, hk⟩ : g ∣ d.val := Nat.gcd_dvd_left _ _
    rw [← natCast_zmod_val d, ← Nat.cast_mul, natCast_eq_zero_iff, hk]
    exact ⟨k, by rw [← mul_assoc, mul_comm m g, ← hm]⟩
  -- hence `m` kills `x`, so `g ∣ x.val`
  have hgx : g ∣ x.val := by
    have hmx := h _ hmd
    rw [← natCast_zmod_val x, ← Nat.cast_mul, natCast_eq_zero_iff] at hmx
    refine (Nat.mul_dvd_mul_iff_left hmpos).1 ?_
    rwa [mul_comm m g, ← hm]
  -- Bézout: `g` is a multiple of `d` in `ZMod n`
  have hbez : (g : ZMod n) = d * (Nat.gcdA d.val n : ZMod n) := by
    have := congrArg (Int.cast : ℤ → ZMod n) (Nat.gcd_eq_gcd_ab d.val n)
    push_cast at this
    rwa [natCast_self, zero_mul, add_zero, natCast_zmod_val] at this
  calc d ∣ (g : ZMod n) := ⟨_, hbez⟩
    _ ∣ (x.val : ZMod n) := Nat.cast_dvd_cast hgx
    _ = x := natCast_zmod_val x

end ZMod

/-- **`ℤ/nℤ` is self-injective**, in the form of Baer's criterion: for `n ≠ 0`, every
`ZMod n`-linear map from an ideal of `ZMod n` to `ZMod n` extends to a linear map on `ZMod n`.
By `Module.Baer.extension_property`, every `ZMod n`-linear map into `ZMod n` then extends along
any injective linear map of `ZMod n`-modules. -/
theorem Module.Baer.zmod_self (n : ℕ) [NeZero n] : Module.Baer (ZMod n) (ZMod n) := by
  have : IsPrincipalIdealRing (ZMod n) :=
    IsPrincipalIdealRing.of_surjective (Int.castRingHom (ZMod n)) ZMod.intCast_surjective
  intro I g
  obtain ⟨d, rfl⟩ : ∃ d, I = Ideal.span {d} := ⟨_, (Ideal.span_singleton_generator I).symm⟩
  have hd : d ∈ Ideal.span {d} := Ideal.mem_span_singleton_self d
  -- the image of the generator is a multiple of the generator
  obtain ⟨y, hy⟩ : d ∣ g ⟨d, hd⟩ := ZMod.dvd_of_forall_mul_eq_zero fun r hr => by
    have : r • (⟨d, hd⟩ : Ideal.span {d}) = 0 := Subtype.ext (by simpa using hr)
    rw [← smul_eq_mul, ← map_smul, this, map_zero]
  refine ⟨LinearMap.toSpanSingleton (ZMod n) (ZMod n) y, fun r hr => ?_⟩
  obtain ⟨s, rfl⟩ := Ideal.mem_span_singleton'.1 hr
  have : (⟨s * d, hr⟩ : Ideal.span {d}) = s • ⟨d, hd⟩ := rfl
  rw [this, map_smul, LinearMap.toSpanSingleton_apply, smul_eq_mul, smul_eq_mul, hy, mul_assoc]
