/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Character
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Prescription
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.CrossedHom
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Procyclic
import TauCeti.Algebra.Group.Subgroup.ZPowers

/-!
# The even-rank dyadic normal form with a `2`-adic exponent

Labute's normal form for the Demushkin relators with `q = 2` of even rank `n` is

  `x₁^{2+α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)`

with a `2`-adic exponent `α ∈ 4ℤ₂` and a level `2 ≤ f ≤ ∞`, the factor `x₃^{2^f}` being absent at
`f = ∞`. The word `TauCeti.demushkinWordTwoEven` carries a natural exponent `2 + a`, which is all
the marked classification needs, because the group presented depends on `α` only through its
valuation. The successive-approximation argument, however, produces the relator with a genuine
`2`-adic exponent, and reading the invariants of the group it presents off that relator needs its
canonical character. This file introduces the word `TauCeti.demushkinWordTwoEvenPadic`, in which
`x₁^{2+α}` is the `2`-adic power `TauCeti.IsProP.padicPow` and the tail is
`x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` for a natural number `q`, even whenever the factor `x₃^q` is
present (`2 < n`), so that `q = 2^f` is Labute's level `f` and `q = 0` is the level `f = ∞`, and
proves Labute's Theorem 4 and its corollary for the pro-`2` group it presents:

* a continuous character has the prescription property exactly when `χ(x₂)(1 + α) = -1`,
  `χ(x₄)(1 - q) = 1` whenever the factor `x₃^q` is present (`2 < n`), and `χ(x_i) = 1` otherwise,
  so the presented group has exactly one such character, the orientation
  `TauCeti.orientationTwoEvenPadic` with those values;
* the image of that character is `{±1} × U^(f)` when `q = 2^f` with `2 ≤ f` and `2^f ∣ α`, the
  twisted subgroup `U^[g]` generated by `-1 + 2^g` when `g = v₂(α) ≥ 2` is smaller than the level
  (including the level `f = ∞`, that is `q = 0`), and `{±1}` when `α = 0` and `q = 0`.

Read on the canonical character of a Demushkin group isomorphic to the presented group, the table
gives the marking of the generators and the image invariant, and in particular identifies the
endpoint of the even-rank dyadic family: a Demushkin group isomorphic to
`⟨x₁, …, xₙ ∣ x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯⟩` with `4 ∣ α` and, as soon as the factor `x₃^q`
is present, `q ∈ {0} ∪ {2^f : f ≥ 2}`, has orientation image `{±1}` only when `α = 0` and, as soon
as the factor `x₃^q` is present (`2 < n`), `q = 0`
(`TauCeti.IsDemushkin.eq_zero_and_eq_zero_of_range_demushkinCharacter_eq_zpowers_neg_one`), in
which case its relator is `x₁² (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)`
(`TauCeti.demushkinWordTwoEvenPadic_zero_zero`, and `x₁² (x₁, x₂)` at `n = 2` by
`TauCeti.demushkinWordTwoEvenPadic_two`).

## Main definitions

* `TauCeti.demushkinWordTwoEvenPadic`: the word `x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)`
  with `α ∈ ℤ₂`, on a tuple of elements of a pro-`2` group; it is the natural-exponent word at
  `α = a` and `q = 2^f` (`TauCeti.demushkinWordTwoEvenPadic_natCast`), it splits off the tail
  relator `x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` as a `q ≠ 2` word
  (`TauCeti.demushkinWordTwoEvenPadic_eq_padicPow_mul_labuteComm_mul`), and at `α = 0`, `q = 0`
  it is the `q ≠ 2` word at `q = 2` (`TauCeti.demushkinWordTwoEvenPadic_zero_zero`).
* `TauCeti.orientationTwoEvenPadic`: the character of the presented group with marked values on
  `x₂` and `x₄` and trivial on the other generators.

## Main results

* `TauCeti.hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff`: a continuous
  character of the presented group has the prescription property exactly when it takes the
  tabulated values.
* `TauCeti.existsUnique_hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic`: the
  presented group has exactly one character with the prescription property.
* `TauCeti.range_eq_unitsPlusMinus_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic`,
  `TauCeti.range_eq_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic_of_not_dvd`,
  `TauCeti.range_eq_zpowers_neg_one_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic`: the
  image table of the canonical character.
* `TauCeti.demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoEvenPadic` and the
  `range_demushkinCharacter_…_of_equiv_demushkinWordTwoEvenPadic` theorems: both tables read on
  the canonical character of a Demushkin group along an isomorphism onto the presented group.
* `TauCeti.IsDemushkin.eq_zero_and_eq_zero_of_range_demushkinCharacter_eq_zpowers_neg_one`: the
  image `{±1}` forces `α = 0`, and `q = 0` whenever the factor `x₃^q` is present.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132, §3,
  Theorem 3, Theorem 4 and its corollary.
* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed., Chapter III, §9.
* The forced-value theorems adapt those of
  `TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Prescription` for the
  natural-exponent word `TauCeti.demushkinWordTwoEven`.
-/

public section

namespace TauCeti

open Finset

universe u

/-! ### The word -/

section Word

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H] [CompactSpace H]
  [TotallyDisconnectedSpace H]

/-- The `q = 2`, `n` even normal-form word `x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` with
a `2`-adic exponent `α`, on a tuple `x : ℕ → H` of elements of a pro-`2` group `H`, with `x 0`
playing the role of `x₁`. The power `x₁^{2+α}` is the `2`-adic power of
`TauCeti.IsProP.padicPow`, and the exponent `q` of `x₃` is the `q`-invariant of the tail relator:
`q = 2^f` is Labute's level `f`, and `q = 0` is the level `f = ∞`, where the factor `x₃^{2^f}` is
absent. At a natural exponent `α = a` and `q = 2^f` the word is `TauCeti.demushkinWordTwoEven a f n`
(`TauCeti.demushkinWordTwoEvenPadic_natCast`). -/
noncomputable def demushkinWordTwoEvenPadic (hH : IsProP 2 H) (α : ℤ_[2]) (q n : ℕ) (x : ℕ → H) :
    H :=
  hH.padicPow (x 0) (2 + α) * labuteComm (x 0) (x 1) * x 2 ^ q *
    ((List.range (n / 2 - 1)).map fun i ↦ labuteComm (x (2 * i + 2)) (x (2 * i + 3))).prod

variable (hH : IsProP 2 H) (α : ℤ_[2]) (q n : ℕ) (x : ℕ → H)

/-- The defining equation of `TauCeti.demushkinWordTwoEvenPadic`. -/
theorem demushkinWordTwoEvenPadic_def :
    demushkinWordTwoEvenPadic hH α q n x =
      hH.padicPow (x 0) (2 + α) * labuteComm (x 0) (x 1) * x 2 ^ q *
        ((List.range (n / 2 - 1)).map fun i ↦ labuteComm (x (2 * i + 2)) (x (2 * i + 3))).prod :=
  (rfl)

/-- At a natural exponent `α = a` and `q = 2^f`, the word is the even dyadic normal-form word
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` with natural exponent. -/
theorem demushkinWordTwoEvenPadic_natCast (a f : ℕ) :
    demushkinWordTwoEvenPadic hH (a : ℤ_[2]) (2 ^ f) n x = demushkinWordTwoEven a f n x := by
  rw [demushkinWordTwoEvenPadic_def, demushkinWordTwoEven_def,
    ← hH.padicPow_natCast (x 0) (2 + a), Nat.cast_add, Nat.cast_ofNat]

/-- At rank two the word is `x₁^{2+α} (x₁, x₂)`: the third generator is out of range, so the
factor `x₃^q` is `1`, and the commutator product beyond `(x₁, x₂)` is empty. -/
theorem demushkinWordTwoEvenPadic_two (hx : x 2 = 1) :
    demushkinWordTwoEvenPadic hH α q 2 x =
      hH.padicPow (x 0) (2 + α) * labuteComm (x 0) (x 1) := by
  simp [demushkinWordTwoEvenPadic_def, hx]

/-- For `n ≥ 2` the word splits as `x₁^{2+α} (x₁, x₂)` times the tail relator
`x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)`, the `q ≠ 2` normal-form word on `n - 2` letters read on the tuple
shifted by two. This is the shape of the relator produced by the successive-approximation argument
for the dyadic relators of even rank. -/
theorem demushkinWordTwoEvenPadic_eq_padicPow_mul_labuteComm_mul (hn : 2 ≤ n) :
    demushkinWordTwoEvenPadic hH α q n x =
      hH.padicPow (x 0) (2 + α) * labuteComm (x 0) (x 1) *
        demushkinWordNeTwo q (n - 2) fun i ↦ x (i + 2) := by
  have hk : (n - 2) / 2 = n / 2 - 1 := by omega
  have hmap : ((List.range (n / 2 - 1)).map fun i ↦
      labuteComm (x (2 * i + 2)) (x (2 * i + 1 + 2))) =
      (List.range (n / 2 - 1)).map fun i ↦ labuteComm (x (2 * i + 2)) (x (2 * i + 3)) :=
    List.map_congr_left fun i _ ↦ by ring_nf
  rw [demushkinWordTwoEvenPadic_def, demushkinWordNeTwo_def, hk, hmap, mul_assoc, mul_assoc]

/-- At `α = 0` and `q = 0` the word is `x₁² (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)`, the `q ≠ 2`
normal-form word at `q = 2`: the even dyadic normal form at level `f = ∞` with `α = 0`. -/
theorem demushkinWordTwoEvenPadic_zero_zero (hn : 2 ≤ n) :
    demushkinWordTwoEvenPadic hH 0 0 n x = demushkinWordNeTwo 2 n x := by
  rw [demushkinWordTwoEvenPadic_eq_padicPow_mul_labuteComm_mul hH 0 0 n x hn, add_zero,
    hH.padicPow_ofNat, demushkinWordNeTwo_eq_pow_mul_labuteComm_mul 2 hn]

variable {K : Type*} [Group K] [TopologicalSpace K] [IsTopologicalGroup K] [CompactSpace K]
  [TotallyDisconnectedSpace K] (hK : IsProP 2 K)

/-- A continuous homomorphism of pro-`2` groups reads the word on the image tuple. -/
theorem map_demushkinWordTwoEvenPadic (φ : H →ₜ* K) :
    φ (demushkinWordTwoEvenPadic hH α q n x) = demushkinWordTwoEvenPadic hK α q n (φ ∘ x) := by
  have hpp : φ (hH.padicPow (x 0) (2 + α)) = hK.padicPow (φ (x 0)) (2 + α) :=
    hH.map_padicPow hK (φ : H →* K) φ.continuous (x 0) (2 + α)
  simp only [demushkinWordTwoEvenPadic_def, map_mul, map_pow, map_list_prod, List.map_map,
    Function.comp_def, map_labuteComm, hpp]

variable {A : Type*} [CommGroup A] [TopologicalSpace A] [IsTopologicalGroup A] [CompactSpace A]
  [TotallyDisconnectedSpace A]

/-- In a commutative pro-`2` group the word is `x₁^{2+α} x₃^q`. -/
theorem demushkinWordTwoEvenPadic_eq_of_commGroup (hA : IsProP 2 A) (y : ℕ → A) :
    demushkinWordTwoEvenPadic hA α q n y = hA.padicPow (y 0) (2 + α) * y 2 ^ q := by
  simp [demushkinWordTwoEvenPadic_def]

/-- A continuous character into a commutative pro-`2` group which is trivial on `x₁` and whose
value on `x₃` has trivial `q`-th power kills the word. -/
theorem map_demushkinWordTwoEvenPadic_eq_one (hA : IsProP 2 A) (φ : H →ₜ* A) (h₀ : φ (x 0) = 1)
    (h₂ : φ (x 2) ^ q = 1) : φ (demushkinWordTwoEvenPadic hH α q n x) = 1 := by
  rw [map_demushkinWordTwoEvenPadic hH α q n x hA φ, demushkinWordTwoEvenPadic_eq_of_commGroup,
    Function.comp_apply, Function.comp_apply, h₀, hA.one_padicPow, h₂, one_mul]

/-- For `α` and `q` even, the word lies in the pro-`2` Frattini subgroup: `x₁^{2+α}` is a `2`-adic
power with even exponent, `x₃^q` is a square and the remaining factors are commutators. -/
theorem demushkinWordTwoEvenPadic_mem_proPFrattini (hα : 2 ∣ α) (hq : 2 ∣ q) :
    demushkinWordTwoEvenPadic hH α q n x ∈ proPFrattini 2 H := by
  have h2 : ((2 : ℕ) : ℤ_[2]) ∣ 2 + α := by exact_mod_cast dvd_add (dvd_refl (2 : ℤ_[2])) hα
  refine mul_mem (mul_mem (mul_mem (hH.padicPow_mem_proPFrattini_of_dvd h2 _)
    (labuteComm_mem_proPFrattini Nat.prime_two _ _)) (pow_mem_proPFrattini_of_dvd hq _))
    (Subgroup.list_prod_mem _ ?_)
  simpa only [List.forall_mem_map] using fun i _ ↦ labuteComm_mem_proPFrattini Nat.prime_two _ _

/-- The value of a crossed homomorphism on the word
`x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)`, with the `2`-adic power `x₁^{2+α}` kept as a
single letter. -/
theorem IsCrossedHom.map_demushkinWordTwoEvenPadic {F' : Type*} [FunLike F' H ℤ_[2]ˣ]
    [MonoidHomClass F' H ℤ_[2]ˣ] {χ : F'} {F : H → ℤ_[2]} (hF : IsCrossedHom χ F) :
    F (demushkinWordTwoEvenPadic hH α q n x) =
      (χ (hH.padicPow (x 0) (2 + α)) : ℤ_[2]) * (χ (x 2) : ℤ_[2]) ^ q *
          ∑ i ∈ range (n / 2 - 1), F (labuteComm (x (2 * i + 2)) (x (2 * i + 3))) +
        (χ (hH.padicPow (x 0) (2 + α)) : ℤ_[2]) *
          ((∑ j ∈ range q, (χ (x 2) : ℤ_[2]) ^ j) * F (x 2)) +
        (χ (hH.padicPow (x 0) (2 + α)) : ℤ_[2]) * F (labuteComm (x 0) (x 1)) +
        F (hH.padicPow (x 0) (2 + α)) := by
  rw [demushkinWordTwoEvenPadic_def]
  simp only [hF.map_mul, hF.map_pow, _root_.map_mul, _root_.map_pow, Units.val_mul,
    Units.val_pow_eq_pow_val, hF.map_list_range_prod_labuteComm, map_labuteComm, labuteComm_eq_one,
    Units.val_one]
  ring

end Word

/-! ### The prescription property on the presented group -/

section Prescription

variable {n : ℕ} (α : ℤ_[2]) (q : ℕ)
  (χ : presentedProP 2 (Fin n)
    {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ)

/-- **The tabulated values give the prescription property** (Labute, Theorem 4, existence). A
continuous character of the pro-`2` group presented by
`x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` with `χ(x₂) (1 + α) = -1`, with
`χ(x₄) (1 - q) = 1` when the factor `x₃^q` is present (`2 < n`), and with `χ(x_i) = 1` otherwise
has the prescription property. -/
theorem hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_of_apply_eq
    (h₁ : (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * (1 + α) = -1)
    (h₃ : 2 < n → (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * (1 - q) = 1)
    (h : ∀ i, i ≠ 1 → i ≠ 3 → χ (presentedProPGen 2 n _ i) = 1) : HasPrescriptionProperty χ := by
  refine presentedProP.hasPrescriptionProperty_of_forall_isCrossedHom_eq_zero
    fun F hFc hF r hr ↦ ?_
  rw [Set.mem_singleton_iff.mp hr]
  have h0 : (χ.comp (presentedProP.mk 2 _)) (freeProPGen 2 n 0) = 1 := by
    rw [presentedProP.comp_mk_freeProPGen]
    exact h 0 zero_ne_one (by omega)
  have h2 : (χ.comp (presentedProP.mk 2 _)) (freeProPGen 2 n 2) = 1 := by
    rw [presentedProP.comp_mk_freeProPGen]
    exact h 2 (by omega) (by omega)
  -- The character is trivial on `x₁^{2+α}`, and `F (x₁^{2+α}) = (2 + α) F (x₁)`.
  have hχpp : (χ.comp (presentedProP.mk 2 _))
      ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 0) (2 + α)) = 1 := by
    have e : (χ.comp (presentedProP.mk 2 _))
        ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 0) (2 + α)) =
        isProP_units_padicInt_two.padicPow ((χ.comp (presentedProP.mk 2 _)) (freeProPGen 2 n 0))
          (2 + α) :=
      (isProP_freeProP 2 (Fin n)).map_padicPow isProP_units_padicInt_two
        (χ.comp (presentedProP.mk 2 _) : freeProP 2 (Fin n) →* ℤ_[2]ˣ)
        (χ.comp (presentedProP.mk 2 _)).continuous _ _
    rw [e, h0, isProP_units_padicInt_two.one_padicPow]
  have hpp := hF.map_padicPow_of_eq_one hFc (isProP_freeProP 2 (Fin n)) h0 (2 + α)
  -- `χ(x₂) F (x₁, x₂) = (1 - χ(x₂)) F x₁`.
  have hc01 := hF.mul_mul_map_labuteComm (freeProPGen 2 n 0) (freeProPGen 2 n 1)
  rw [h0, Units.val_one, one_mul, sub_self, zero_mul, add_zero] at hc01
  rw [hF.map_demushkinWordTwoEvenPadic, hχpp, hpp, h2, Units.val_one, one_pow, one_mul,
    one_mul, one_mul]
  rcases le_or_gt 4 n with hn | hn
  · -- `χ(x₄) F (x₃, x₄) = (1 - χ(x₄)) F x₃`, and the other commutator factors are killed.
    have hc23 := hF.mul_mul_map_labuteComm (freeProPGen 2 n 2) (freeProPGen 2 n 3)
    rw [h2, Units.val_one, one_mul, sub_self, zero_mul, add_zero] at hc23
    rw [Finset.sum_eq_single 0 (fun i _ hi ↦ hF.map_labuteComm_eq_zero_of_eq_one
        (by rw [presentedProP.comp_mk_freeProPGen]; exact h _ (by omega) (by omega))
        (by rw [presentedProP.comp_mk_freeProPGen]; exact h _ (by omega) (by omega)))
      fun h0' ↦ absurd (mem_range.2 (by omega)) h0']
    simp only [Nat.mul_zero, Nat.zero_add, one_pow, sum_const, card_range, nsmul_eq_mul, mul_one]
    rw [presentedProP.comp_mk_freeProPGen] at hc01 hc23
    refine (Units.mul_right_eq_zero (χ (presentedProPGen 2 n _ 3))).1
      ((Units.mul_right_eq_zero (χ (presentedProPGen 2 n _ 1))).1 ?_)
    linear_combination (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * hc23 +
      (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * hc01 -
      (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * F (freeProPGen 2 n 2) * h₃ (by omega) +
      (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * F (freeProPGen 2 n 0) * h₁
  · -- For `n ≤ 3` the word is `x₁^{2+α} (x₁, x₂) x₃^q`, and the factor `x₃^q` contributes nothing:
    -- at `n = 3` the generator `x₄` is `1`, so the clause `χ(x₄)(1 - q) = 1` forces `q = 0`, and
    -- for `n ≤ 2` the generator `x₃` is `1`.
    have hterm : (∑ j ∈ range q, (1 : ℤ_[2]) ^ j) * F (freeProPGen 2 n 2) = 0 := by
      rcases le_or_gt 3 n with hn₃ | hn₃
      · have hq : q = 0 := by
          have h₃' := h₃ (by omega)
          rw [presentedProPGen_eq_one_of_le 2 n _ (by omega), map_one, Units.val_one, one_mul,
            sub_eq_self] at h₃'
          exact_mod_cast h₃'
        rw [hq, sum_range_zero, zero_mul]
      · rw [freeProPGen_eq_one_of_le 2 (by omega), hF.map_one, mul_zero]
    rw [presentedProP.comp_mk_freeProPGen] at hc01
    rw [(by omega : n / 2 - 1 = 0), sum_range_zero, zero_add, hterm, zero_add, one_mul]
    refine (Units.mul_right_eq_zero (χ (presentedProPGen 2 n _ 1))).1 ?_
    linear_combination hc01 + F (freeProPGen 2 n 0) * h₁

/-- **The prescription property forces the tabulated values** (Labute, Theorem 4). For `α` even,
`n ≥ 2` even and `q` even whenever the factor `x₃^q` is present (`2 < n`), a continuous character
of the pro-`2` group presented by `x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` has the
prescription property exactly when `χ(x₂) (1 + α) = -1`, `χ(x₄) (1 - q) = 1` when the factor
`x₃^q` is present, and `χ(x_i) = 1` for every other `i`. At `n = 2` the relator is
`x₁^{2+α} (x₁, x₂)` whatever `q` is, and the conditions read `χ(x₂) (1 + α) = -1` and
`χ(x₁) = 1`. -/
theorem hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff (hα : 2 ∣ α)
    (hq : 2 < n → 2 ∣ q) (hn : Even n) (hn₁ : 1 < n) :
    HasPrescriptionProperty χ ↔
      (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * (1 + α) = -1 ∧
        (2 < n → (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * (1 - q) = 1) ∧
        ∀ i, i ≠ 1 → i ≠ 3 → χ (presentedProPGen 2 n _ i) = 1 := by
  refine ⟨fun hχ ↦ ?_, fun h ↦
    hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_of_apply_eq α q χ h.1 h.2.1
      h.2.2⟩
  have hrels : ({demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} :
      Set (freeProP 2 (Fin n))) ⊆ proPFrattini 2 (freeProP 2 (Fin n)) := by
    refine Set.singleton_subset_iff.2 ?_
    rcases lt_or_ge 2 n with hn₂ | hn₂
    · exact demushkinWordTwoEvenPadic_mem_proPFrattini _ α q n _ hα (hq hn₂)
    · -- At `n = 2` the generator `x₃` is `1`, so the word is the one with `q = 0`.
      obtain rfl : n = 2 := by omega
      have h2 : freeProPGen 2 2 2 = 1 := freeProPGen_eq_one_of_le 2 le_rfl
      rw [demushkinWordTwoEvenPadic_two _ _ _ _ h2, ← demushkinWordTwoEvenPadic_two _ α 0 _ h2]
      exact demushkinWordTwoEvenPadic_mem_proPFrattini _ α 0 2 _ hα (dvd_zero 2)
  obtain ⟨k, hk⟩ := hn
  -- For the crossed homomorphism `F` with `F (x_i) = δ_{ij}`, `j ≥ 2`, only the commutator factor
  -- containing `x_j` contributes to the value on the relator.
  have hsum : ∀ j, 2 ≤ j → j < n → ∀ F : freeProP 2 (Fin n) → ℤ_[2],
      IsCrossedHom (χ.comp (presentedProP.mk 2 _)) F →
      (∀ i, F (freeProPGen 2 n i) = if i = j then 1 else 0) →
      ∑ i ∈ range (n / 2 - 1),
          F (labuteComm (freeProPGen 2 n (2 * i + 2)) (freeProPGen 2 n (2 * i + 3))) =
        F (labuteComm (freeProPGen 2 n (2 * ((j - 2) / 2) + 2))
          (freeProPGen 2 n (2 * ((j - 2) / 2) + 3))) :=
    fun j hj₂ hj F hF hFv ↦ Finset.sum_eq_single _
      (fun i _ hi ↦ hF.map_labuteComm_eq_zero_of_eq_zero
        (by rw [hFv, ite_eq_right (by omega)]) (by rw [hFv, ite_eq_right (by omega)]))
      fun h0 ↦ absurd (mem_range.2 (by omega)) h0
  -- For `j ≤ 2` no commutator factor beyond `(x₁, x₂)` contributes.
  have hsum₀ : ∀ j, j < 2 → ∀ F : freeProP 2 (Fin n) → ℤ_[2],
      IsCrossedHom (χ.comp (presentedProP.mk 2 _)) F →
      (∀ i, F (freeProPGen 2 n i) = if i = j then 1 else 0) →
      ∑ i ∈ range (n / 2 - 1),
        F (labuteComm (freeProPGen 2 n (2 * i + 2)) (freeProPGen 2 n (2 * i + 3))) = 0 :=
    fun j hj F hF hFv ↦ Finset.sum_eq_zero fun i _ ↦ hF.map_labuteComm_eq_zero_of_eq_zero
      (by rw [hFv, ite_eq_right (by omega)]) (by rw [hFv, ite_eq_right (by omega)])
  -- For `j ≥ 4` the commutator factor `(x_a, x_b)` containing `x_j` has `F (x_a, x_b) = 0`; the
  -- `2`-adic power `x₁^{2+α}` is killed because `F (x₁) = 0`.
  have hval : ∀ j, 3 ≤ j → j < n → ∀ F : freeProP 2 (Fin n) → ℤ_[2], Continuous F →
      IsCrossedHom (χ.comp (presentedProP.mk 2 _)) F →
      (∀ i, F (freeProPGen 2 n i) = if i = j then 1 else 0) →
      F (demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)) = 0 →
      F (labuteComm (freeProPGen 2 n (2 * ((j - 2) / 2) + 2))
        (freeProPGen 2 n (2 * ((j - 2) / 2) + 3))) = 0 := by
    intro j hj₃ hj F hFc hF hFv hFr
    rw [hF.map_demushkinWordTwoEvenPadic, hsum j (by omega) hj F hF hFv,
      hF.map_labuteComm_eq_zero_of_eq_zero (x := freeProPGen 2 n 0) (y := freeProPGen 2 n 1)
        (by rw [hFv, ite_eq_right (by omega)]) (by rw [hFv, ite_eq_right (by omega)]),
      hF.map_padicPow_eq_zero_of_eq_zero hFc _ (by rw [hFv, ite_eq_right (by omega)])] at hFr
    simp only [hFv 2, ite_eq_right (show (2 : ℕ) ≠ j by omega), mul_zero, add_zero,
      ← Units.val_pow_eq_pow_val, ← Units.val_mul] at hFr
    exact (Units.mul_right_eq_zero _).1 hFr
  -- `j = 2`: `χ(x₁) = 1`.
  have hx0 : χ (presentedProPGen 2 n _ 0) = 1 := by
    obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
      hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels hn₁
    have hr := hFr _ rfl
    rw [hF.map_demushkinWordTwoEvenPadic, hsum₀ 1 one_lt_two F hF hFv,
      hF.map_padicPow_eq_zero_of_eq_zero hFc _ (by rw [hFv, ite_eq_right zero_ne_one])] at hr
    simp only [hFv 2, ite_eq_right (show (2 : ℕ) ≠ 1 by omega), mul_zero, add_zero,
      zero_add] at hr
    rw [← presentedProP.comp_mk_freeProPGen]
    exact hF.eq_one_of_map_labuteComm_eq_zero_right (by rw [hFv, ite_eq_right zero_ne_one])
      (by rw [hFv, ite_eq_left rfl]) ((Units.mul_right_eq_zero _).1 hr)
  have hx0' : (χ.comp (presentedProP.mk 2 _)) (freeProPGen 2 n 0) = 1 := by
    rw [presentedProP.comp_mk_freeProPGen]
    exact hx0
  -- `j = 4`: `χ(x₃) = 1`; at `n = 2` the generator `x₃` is `1`.
  have hx2 : χ (presentedProPGen 2 n _ 2) = 1 := by
    rcases le_or_gt 4 n with hn₄ | hn₄
    · obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
        hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels
          (by omega : 3 < n)
      have hc := hval 3 le_rfl (by omega) F hFc hF hFv (hFr _ rfl)
      rw [(by omega : 2 * ((3 - 2) / 2) + 2 = 2), (by omega : 2 * ((3 - 2) / 2) + 3 = 3)] at hc
      rw [← presentedProP.comp_mk_freeProPGen]
      exact hF.eq_one_of_map_labuteComm_eq_zero_right (by rw [hFv, ite_eq_right (by omega)])
        (by rw [hFv, ite_eq_left rfl]) hc
    · rw [presentedProPGen_eq_one_of_le 2 n _ (by omega), map_one]
  refine ⟨?_, ?_, fun i hi₁ hi₃ ↦ ?_⟩
  · -- `j = 1`: `2 + α + χ(x₂)⁻¹ - 1 = 0`.
    obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
      hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels (by omega : 0 < n)
    have hr := hFr _ rfl
    have hχpp : (χ.comp (presentedProP.mk 2 _))
        ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 0) (2 + α)) = 1 := by
      have e : (χ.comp (presentedProP.mk 2 _))
          ((isProP_freeProP 2 (Fin n)).padicPow (freeProPGen 2 n 0) (2 + α)) =
          isProP_units_padicInt_two.padicPow
            ((χ.comp (presentedProP.mk 2 _)) (freeProPGen 2 n 0)) (2 + α) :=
        (isProP_freeProP 2 (Fin n)).map_padicPow isProP_units_padicInt_two
          (χ.comp (presentedProP.mk 2 _) : freeProP 2 (Fin n) →* ℤ_[2]ˣ)
          (χ.comp (presentedProP.mk 2 _)).continuous _ _
      rw [e, hx0', isProP_units_padicInt_two.one_padicPow]
    rw [hF.map_demushkinWordTwoEvenPadic, hsum₀ 0 two_pos F hF hFv, hχpp,
      hF.map_padicPow_of_eq_one hFc _ hx0', Units.val_one] at hr
    simp only [hFv 0, hFv 2, ite_eq_left, ite_eq_right (show (2 : ℕ) ≠ 0 by omega), one_mul,
      mul_one, mul_zero, zero_add, add_zero] at hr
    have hc := hF.mul_mul_map_labuteComm (freeProPGen 2 n 0) (freeProPGen 2 n 1)
    rw [presentedProP.comp_mk_freeProPGen, presentedProP.comp_mk_freeProPGen, hx0, Units.val_one,
      one_mul, sub_self, zero_mul, add_zero, hFv 0, ite_eq_left rfl, mul_one] at hc
    linear_combination (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * hr - hc
  · -- `j = 3`: `q + χ(x₄)⁻¹ - 1 = 0`.
    intro hn₂
    obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
      hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels hn₂
    have hr := hFr _ rfl
    rw [hF.map_demushkinWordTwoEvenPadic, hsum 2 le_rfl hn₂ F hF hFv,
      hF.map_labuteComm_eq_zero_of_eq_zero (x := freeProPGen 2 n 0) (y := freeProPGen 2 n 1)
        (by rw [hFv, ite_eq_right (by omega)]) (by rw [hFv, ite_eq_right (by omega)]),
      hF.map_padicPow_eq_zero_of_eq_zero hFc _ (by rw [hFv, ite_eq_right (by omega)]),
      presentedProP.comp_mk_freeProPGen, hx2, Units.val_one] at hr
    simp only [Nat.sub_self, Nat.zero_div, Nat.zero_add, hFv 2, ite_eq_left, one_pow, mul_one,
      mul_zero, add_zero, sum_const, card_range, nsmul_eq_mul, ← mul_add] at hr
    replace hr := (Units.mul_right_eq_zero _).1 hr
    have hc := hF.mul_mul_map_labuteComm (freeProPGen 2 n 2) (freeProPGen 2 n 3)
    rw [presentedProP.comp_mk_freeProPGen, presentedProP.comp_mk_freeProPGen, hx2,
      Units.val_one, one_mul, sub_self, zero_mul, add_zero, hFv 2, ite_eq_left rfl, mul_one] at hc
    linear_combination hc - (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * hr
  · by_cases hin : i < n
    · rcases Nat.lt_or_ge i 4 with h4 | h4
      · rcases (by omega : i = 0 ∨ i = 2) with rfl | rfl
        · exact hx0
        · exact hx2
      -- `j ≥ 5`: the partner of `x_j` in its commutator factor has `χ = 1`.
      rw [← presentedProP.comp_mk_freeProPGen]
      rcases Nat.even_or_odd i with ⟨m, hm⟩ | ⟨m, hm⟩
      · obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
          hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels
            (by omega : i + 1 < n)
        have hc := hval (i + 1) (by omega) (by omega) F hFc hF hFv (hFr _ rfl)
        rw [(by omega : 2 * ((i + 1 - 2) / 2) + 2 = i),
          (by omega : 2 * ((i + 1 - 2) / 2) + 3 = i + 1)] at hc
        exact hF.eq_one_of_map_labuteComm_eq_zero_right (by rw [hFv, ite_eq_right (by omega)])
          (by rw [hFv, ite_eq_left rfl]) hc
      · obtain ⟨F, hFc, hF, hFv, hFr⟩ :=
          hχ.exists_continuous_isCrossedHom_comp_mk_forall_freeProPGen_eq_ite hrels
            (by omega : i - 1 < n)
        have hc := hval (i - 1) (by omega) (by omega) F hFc hF hFv (hFr _ rfl)
        rw [(by omega : 2 * ((i - 1 - 2) / 2) + 2 = i - 1),
          (by omega : 2 * ((i - 1 - 2) / 2) + 3 = i)] at hc
        exact hF.eq_one_of_map_labuteComm_eq_zero_left (by rw [hFv, ite_eq_left rfl])
          (by rw [hFv, ite_eq_right (by omega)]) hc
    · rw [presentedProPGen_eq_one_of_le 2 n _ (not_lt.1 hin), map_one]

end Prescription

/-! ### The orientation of the presented group -/

section Orientation

variable (α : ℤ_[2]) (q n : ℕ) (v u : ℤ_[2]ˣ)

/-- **The orientation of the even dyadic normal form with `2`-adic exponent and marked values `v`,
`u`**: the continuous character of the pro-`2` group presented on `n` generators by
`x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` with `χ(x₂) = v`, `χ(x₄) = u` and `χ(x_i) = 1`
otherwise. The canonical character is the case `v = -(1 + α)⁻¹`, `u = (1 - q)⁻¹`. -/
noncomputable def orientationTwoEvenPadic :
    presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} →ₜ*
        ℤ_[2]ˣ :=
  presentedProP.lift (freeProP.lift isProP_units_padicInt_two
      fun i : Fin n ↦ if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordTwoEvenPadic_eq_one _ α q n _ isProP_units_padicInt_two _ ?_ ?_ <;>
      rw [freeProP.lift_freeProPGen] <;> split_ifs <;> simp_all

/-- The value of the orientation on the generators. -/
@[simp]
theorem orientationTwoEvenPadic_of (i : Fin n) :
    orientationTwoEvenPadic α q n v u (presentedProP.of 2 _ i) =
      if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1 := by
  rw [orientationTwoEvenPadic, presentedProP.lift_of, freeProP.lift_of]

/-- The orientation takes `x₂` to its marked value `v`. -/
theorem orientationTwoEvenPadic_presentedProPGen_one (hn : 1 < n) :
    orientationTwoEvenPadic α q n v u (presentedProPGen 2 n _ 1) = v := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoEvenPadic_of]
  simp

/-- The orientation takes `x₄` to its marked value `u`. -/
theorem orientationTwoEvenPadic_presentedProPGen_three (hn : 3 < n) :
    orientationTwoEvenPadic α q n v u (presentedProPGen 2 n _ 3) = u := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoEvenPadic_of]
  simp

/-- The orientation is trivial on every generator other than `x₂` and `x₄`. -/
@[simp]
theorem orientationTwoEvenPadic_presentedProPGen_of_ne {i : ℕ} (hi₁ : i ≠ 1) (hi₃ : i ≠ 3) :
    orientationTwoEvenPadic α q n v u (presentedProPGen 2 n _ i) = 1 := by
  rw [map_presentedProPGen]
  split_ifs <;> simp [hi₁, hi₃]

/-- The image of the orientation is the closed subgroup generated by its marked values `v` and
`u`, as soon as the generator `x₄` exists. -/
theorem range_orientationTwoEvenPadic (hn : 3 < n) :
    (orientationTwoEvenPadic α q n v u).toMonoidHom.range =
      (Subgroup.zpowers v ⊔ Subgroup.zpowers u).topologicalClosure := by
  refine MonoidHom.range_eq_topologicalClosure_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (orientationTwoEvenPadic α q n v u).continuous
    (MonoidHom.isClosed_range_of_continuous (orientationTwoEvenPadic α q n v u).continuous) ?_
    (sup_le
      (Subgroup.zpowers_le.mpr
        ⟨_, orientationTwoEvenPadic_presentedProPGen_one α q n v u (by omega)⟩)
      (Subgroup.zpowers_le.mpr
        ⟨_, orientationTwoEvenPadic_presentedProPGen_three α q n v u hn⟩))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, orientationTwoEvenPadic_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
  · exact one_mem _

/-- For `1 < n ≤ 3` the image of the orientation is the closed subgroup generated by its marked
value `v`: the generator `x₂` exists but `x₄` does not. -/
theorem range_orientationTwoEvenPadic_of_le_three (hn : 1 < n) (hn' : n ≤ 3) :
    (orientationTwoEvenPadic α q n v u).toMonoidHom.range =
      (Subgroup.zpowers v).topologicalClosure := by
  refine MonoidHom.range_eq_topologicalClosure_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (orientationTwoEvenPadic α q n v u).continuous
    (MonoidHom.isClosed_range_of_continuous (orientationTwoEvenPadic α q n v u).continuous) ?_
    (Subgroup.zpowers_le.mpr ⟨_, orientationTwoEvenPadic_presentedProPGen_one α q n v u hn⟩)
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, orientationTwoEvenPadic_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_zpowers _)
  · exact absurd i.isLt (by omega)
  · exact one_mem _

/-- **The orientation with the canonical values has the prescription property**: for `3 < n`, the
character with `χ(x₂) = v`, `v (1 + α) = -1`, `χ(x₄) = u`, `u (1 - q) = 1`, and `χ(x_i) = 1`
otherwise. -/
theorem hasPrescriptionProperty_orientationTwoEvenPadic (hn₃ : 3 < n)
    (hv : (v : ℤ_[2]) * (1 + α) = -1) (hu : (u : ℤ_[2]) * (1 - q) = 1) :
    HasPrescriptionProperty (orientationTwoEvenPadic α q n v u) :=
  hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_of_apply_eq α q _
    (by rw [orientationTwoEvenPadic_presentedProPGen_one α q n v u (by omega)]; exact hv)
    (fun _ ↦ by rw [orientationTwoEvenPadic_presentedProPGen_three α q n v u hn₃]; exact hu)
    fun _ hi₁ hi₃ ↦ orientationTwoEvenPadic_presentedProPGen_of_ne α q n v u hi₁ hi₃

/-- **The orientation with the canonical value has the prescription property in rank two**: for
the relator `x₁^{2+α} (x₁, x₂)`, the character with `χ(x₂) = v`, `v (1 + α) = -1`, and `χ(x₁) = 1`,
whatever `q`, which does not enter the rank-two relator, and the unused marked value `u`. -/
theorem hasPrescriptionProperty_orientationTwoEvenPadic_two (hv : (v : ℤ_[2]) * (1 + α) = -1) :
    HasPrescriptionProperty (orientationTwoEvenPadic α q 2 v u) :=
  hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_of_apply_eq α q _
    (by rw [orientationTwoEvenPadic_presentedProPGen_one α q 2 v u one_lt_two]; exact hv)
    (fun h ↦ absurd h (by norm_num))
    fun _ hi₁ hi₃ ↦ orientationTwoEvenPadic_presentedProPGen_of_ne α q 2 v u hi₁ hi₃

variable {α q n}

/-- **Uniqueness of the canonical character**: for `α` even, `n ≥ 2` even and `q` even whenever
the factor `x₃^q` is present (`2 < n`), a character with the prescription property is the
orientation with marked values its own values `χ(x₂)` and `χ(x₄)`. -/
theorem eq_orientationTwoEvenPadic_of_hasPrescriptionProperty (hα : 2 ∣ α) (hq : 2 < n → 2 ∣ q)
    (hn : Even n) (hn₁ : 1 < n)
    {χ : presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ}
    (hχ : HasPrescriptionProperty χ) :
    χ = orientationTwoEvenPadic α q n (χ (presentedProPGen 2 n _ 1))
      (χ (presentedProPGen 2 n _ 3)) := by
  obtain ⟨-, -, h⟩ :=
    (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff α q χ hα hq hn hn₁).1 hχ
  refine presentedProP.hom_ext_of fun i ↦ ?_
  rw [orientationTwoEvenPadic_of, ← presentedProPGen_val]
  split_ifs with hi₁ hi₃
  · rw [hi₁]
  · rw [hi₃]
  · exact h i hi₁ hi₃

/-- **The presented group has exactly one character with the prescription property** (Labute,
Theorem 4, for the normal form `x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)` with `α` even,
`n ≥ 2` even and `q` even whenever the factor `x₃^q` is present (`2 < n`)): the orientation with
`χ(x₂) = -(1 + α)⁻¹` and `χ(x₄) = (1 - q)⁻¹`. -/
theorem existsUnique_hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic (hα : 2 ∣ α)
    (hq : 2 < n → 2 ∣ q) (hn : Even n) (hn₁ : 1 < n) :
    ∃! χ : presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ,
      HasPrescriptionProperty χ := by
  obtain ⟨v, hv⟩ := exists_val_mul_one_add_eq_neg_one hα
  -- The marked value on `x₄` is `(1 - q)⁻¹` when the factor `x₃^q` is present; at `n = 2` the
  -- generator `x₄` does not exist and any value, say `1`, will do.
  obtain ⟨u, hu⟩ : ∃ u : ℤ_[2]ˣ, 2 < n → (u : ℤ_[2]) * (1 - q) = 1 := by
    by_cases hn₂ : 2 < n
    · have hunit : IsUnit (1 - (q : ℤ_[2])) := by
        rw [sub_eq_add_neg]
        exact PadicInt.isUnit_one_add_of_dvd (dvd_neg.mpr
          (by simpa using (Nat.cast_dvd_cast (hq hn₂) : ((2 : ℕ) : ℤ_[2]) ∣ (q : ℤ_[2]))))
      exact ⟨hunit.unit⁻¹, fun _ ↦ hunit.val_inv_mul⟩
    · exact ⟨1, fun h ↦ absurd h hn₂⟩
  refine ⟨orientationTwoEvenPadic α q n v u, ?_, fun χ hχ ↦ ?_⟩
  · rcases le_or_gt 4 n with hn₄ | hn₄
    · exact hasPrescriptionProperty_orientationTwoEvenPadic α q n v u (by omega) hv
        (hu (by omega))
    · obtain rfl : n = 2 := by obtain ⟨k, hk⟩ := hn; omega
      exact hasPrescriptionProperty_orientationTwoEvenPadic_two α q v u hv
  · obtain ⟨h₁, h₃, h⟩ :=
      (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff α q χ hα hq hn hn₁).1 hχ
    refine presentedProP.hom_ext_of fun i ↦ ?_
    have hi := i.isLt
    rw [orientationTwoEvenPadic_of, ← presentedProPGen_val]
    split_ifs with hi₁ hi₃
    · rw [hi₁]
      exact Units.val_inj.1 (by linear_combination (χ (presentedProPGen 2 n _ 1) : ℤ_[2]) * hv -
        (v : ℤ_[2]) * h₁)
    · rw [hi₃]
      exact Units.val_inj.1 (by linear_combination (u : ℤ_[2]) * h₃ (by omega) -
        (χ (presentedProPGen 2 n _ 3) : ℤ_[2]) * hu (by omega))
    · exact h i hi₁ hi₃

end Orientation

/-! ### The image table -/

section ImageTable

variable {α : ℤ_[2]} {q n : ℕ}
  {χ : presentedProP 2 (Fin n)
    {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ}

/-- **The image of the canonical character when `q = 2^f` and `2^f ∣ α` is `{±1} × U^(f)`**, for
`f ≥ 2` and `n ≥ 4` even: any character with the prescription property takes `x₂` to
`-(1 + α)⁻¹ ∈ -U^(f)` and `x₄` to `(1 - 2^f)⁻¹`. This includes `α = 0`. -/
theorem range_eq_unitsPlusMinus_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic {f : ℕ}
    (hf : 2 ≤ f) (hq : q = 2 ^ f) (hn : Even n) (hn₃ : 3 < n) (hα : (2 : ℤ_[2]) ^ f ∣ α)
    (hχ : HasPrescriptionProperty χ) : χ.toMonoidHom.range = unitsPlusMinus f := by
  subst hq
  have hα₂ : 2 ∣ α := (dvd_pow_self 2 (by omega : f ≠ 0)).trans hα
  have hq₂ : 2 < n → 2 ∣ 2 ^ f := fun _ ↦ dvd_pow_self 2 (by omega)
  obtain ⟨h₁, h₃, -⟩ :=
    (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff α _ χ hα₂ hq₂ hn
      (by omega)).1 hχ
  replace h₃ := h₃ (by omega)
  push_cast at h₃
  have h := eq_orientationTwoEvenPadic_of_hasPrescriptionProperty hα₂ hq₂ hn (by omega) hχ
  have hr := range_orientationTwoEvenPadic α (2 ^ f) n (χ (presentedProPGen 2 n _ 1))
    (χ (presentedProPGen 2 n _ 3)) hn₃
  rw [← h] at hr
  rw [hr, topologicalClosure_zpowers_sup_zpowers_eq_unitsPlusMinus_of_dvd hf h₁ h₃ hα]

/-- **The image of the canonical character when `v₂(α) = g` is smaller than the level is the
twisted subgroup `U^[g]`**, the closed subgroup generated by `-1 + 2^g`, for `g ≥ 2` and `n ≥ 4`
even. The level is encoded by `q`, and the hypothesis `2^(g+1) ∣ q` is stated for every such
multiple; it includes the normal-form cases `q = 2^f` with `f > g` and `q = 0`, the level `f = ∞`.
The character takes `x₂` to `-(1 + α)⁻¹`, which generates `U^[g]`, and `x₄` to
`(1 - q)⁻¹ ∈ U^(g+1) ≤ U^[g]`. -/
theorem range_eq_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic_of_not_dvd {g : ℕ}
    (hg : 2 ≤ g) (hαg : (2 : ℤ_[2]) ^ g ∣ α) (hαg' : ¬ (2 : ℤ_[2]) ^ (g + 1) ∣ α)
    (hqg : (2 : ℤ_[2]) ^ (g + 1) ∣ (q : ℤ_[2])) (hn : Even n) (hn₃ : 3 < n) {w : ℤ_[2]ˣ}
    (hw : (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g) (hχ : HasPrescriptionProperty χ) :
    χ.toMonoidHom.range = (Subgroup.zpowers w).topologicalClosure := by
  have hα₂ : 2 ∣ α := (dvd_pow_self 2 (by omega : g ≠ 0)).trans hαg
  -- `2 ^ (g + 1) ∣ q` in `ℤ₂` makes `q` even.
  have hq : 2 ∣ q := by
    have h2 : ((2 : ℕ) : ℤ_[2]) ∣ ((q : ℤ) : ℤ_[2]) := by
      exact_mod_cast (dvd_pow_self (2 : ℤ_[2]) (by omega : g + 1 ≠ 0)).trans hqg
    exact_mod_cast (PadicInt.norm_int_lt_one_iff_dvd (q : ℤ)).1
      ((PadicInt.norm_lt_one_iff_dvd _).2 h2)
  obtain ⟨h₁, h₃, -⟩ :=
    (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff α q χ hα₂ (fun _ ↦ hq) hn
      (by omega)).1 hχ
  replace h₃ := h₃ (by omega)
  have hv := (neg_mem_unitsPrincipal_iff_of_val_mul_one_add_eq_neg_one h₁).mpr hαg
  have hv' : -χ (presentedProPGen 2 n _ 1) ∉ unitsPrincipal 2 (g + 1) := fun h ↦
    hαg' ((neg_mem_unitsPrincipal_iff_of_val_mul_one_add_eq_neg_one h₁).mp h)
  have hu : χ (presentedProPGen 2 n _ 3) ∈ unitsPrincipal 2 (g + 1) :=
    (mem_unitsPrincipal_iff_of_val_mul_one_sub_eq_one h₃).mpr (by exact_mod_cast hqg)
  have h := eq_orientationTwoEvenPadic_of_hasPrescriptionProperty hα₂ (fun _ ↦ hq) hn (by omega) hχ
  have hr := range_orientationTwoEvenPadic α q n (χ (presentedProPGen 2 n _ 1))
    (χ (presentedProPGen 2 n _ 3)) hn₃
  rw [← h] at hr
  rw [hr, topologicalClosure_zpowers_sup_zpowers_eq_of_mem_unitsPrincipal_succ hg hv hv' hu,
    (topologicalClosure_zpowers_two_eq_iff hg hg hv hv' (neg_mem_unitsPrincipal_two_of_val_eq hw)
      (neg_notMem_unitsPrincipal_two_succ_of_val_eq hw)).mpr rfl]

/-- **The image of the canonical character at `α = 0` and `q = 0` is `{±1}`**, for `n ≥ 2` even,
`q = 0` being required only when the factor `x₃^q` is present (`2 < n`): the relator is
`x₁² (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)`, the endpoint `f = ∞` of the even dyadic family, and the
character takes `x₂` to `-1` and every other generator to `1`. -/
theorem range_eq_zpowers_neg_one_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic (hα : α = 0)
    (hq : 2 < n → q = 0) (hn : Even n) (hn₁ : 1 < n) (hχ : HasPrescriptionProperty χ) :
    χ.toMonoidHom.range = Subgroup.zpowers (-1) := by
  subst hα
  have hq₂ : 2 < n → 2 ∣ q := fun h ↦ (hq h) ▸ dvd_zero 2
  obtain ⟨h₁, h₃, -⟩ :=
    (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff 0 q χ (dvd_zero 2) hq₂ hn
      hn₁).1 hχ
  have hv : χ (presentedProPGen 2 n _ 1) = -1 := Units.ext (by simpa using h₁)
  have h := eq_orientationTwoEvenPadic_of_hasPrescriptionProperty (dvd_zero 2) hq₂ hn hn₁ hχ
  rw [hv] at h
  rcases le_or_gt 4 n with hn₄ | hn₄
  · obtain rfl : q = 0 := hq (by omega)
    have hu : χ (presentedProPGen 2 n _ 3) = 1 := Units.ext (by simpa using h₃ (by omega))
    rw [hu] at h
    rw [h, range_orientationTwoEvenPadic 0 0 n _ _ (by omega), Subgroup.zpowers_one_eq_bot,
      sup_bot_eq, topologicalClosure_zpowers_neg_one]
  · rw [h, range_orientationTwoEvenPadic_of_le_three 0 q n _ _ hn₁ (by omega),
      topologicalClosure_zpowers_neg_one]

end ImageTable

/-! ### The tables on the canonical character of a Demushkin group -/

section Demushkin

variable {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G] (hG : IsDemushkin 2 G) {α : ℤ_[2]} {q n : ℕ}
include hG

/-- **The character table on the canonical character.** Along an isomorphism
`e : G ≃ₜ* ⟨x₁, …, xₙ ∣ x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)⟩`, for `α` even, `n ≥ 2`
even and `q` even whenever the factor `x₃^q` is present (`2 < n`), the canonical character of `G`
satisfies `χ(x₂)(1 + α) = -1`, `χ(x₄)(1 - q) = 1` when the factor `x₃^q` is present, and
`χ(x_i) = 1` otherwise, the generators being read back in `G` through `e⁻¹`. -/
theorem demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoEvenPadic (hα : 2 ∣ α)
    (hq : 2 < n → 2 ∣ q) (hn : Even n) (hn₁ : 1 < n)
    (e : G ≃ₜ* presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)}) :
    (demushkinCharacter hG (e.symm (presentedProPGen 2 n _ 1)) : ℤ_[2]) * (1 + α) = -1 ∧
      (2 < n → (demushkinCharacter hG (e.symm (presentedProPGen 2 n _ 3)) : ℤ_[2]) * (1 - q) = 1) ∧
      ∀ i, i ≠ 1 → i ≠ 3 → demushkinCharacter hG (e.symm (presentedProPGen 2 n _ i)) = 1 :=
  (hasPrescriptionProperty_presentedProP_demushkinWordTwoEvenPadic_iff α q _ hα hq hn hn₁).1
    (hasPrescriptionProperty_demushkinCharacter hG).comp_equiv

/-- **A Demushkin group isomorphic to the even dyadic normal form with `q = 2^f` and `2^f ∣ α` has
orientation image `{±1} × U^(f)`**, for `f ≥ 2` and `n ≥ 4` even. -/
theorem range_demushkinCharacter_eq_unitsPlusMinus_of_equiv_demushkinWordTwoEvenPadic {f : ℕ}
    (hf : 2 ≤ f) (hq : q = 2 ^ f) (hn : Even n) (hn₃ : 3 < n) (hα : (2 : ℤ_[2]) ^ f ∣ α)
    (e : G ≃ₜ* presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)}) :
    (demushkinCharacter hG).toMonoidHom.range = unitsPlusMinus f :=
  range_demushkinCharacter_eq_of_equiv hG e fun _ ↦
    range_eq_unitsPlusMinus_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic hf hq hn hn₃ hα

/-- **A Demushkin group isomorphic to the even dyadic normal form with `v₂(α) = g` below the level
has orientation image `U^[g]`**, the closed subgroup generated by `-1 + 2^g`, for `g ≥ 2` and
`n ≥ 4` even; the hypothesis `2^(g+1) ∣ q` is stated for every such multiple and includes the
normal-form cases `q = 2^f` with `f > g` and `q = 0`. -/
theorem range_demushkinCharacter_eq_of_equiv_demushkinWordTwoEvenPadic_of_not_dvd {g : ℕ}
    (hg : 2 ≤ g) (hαg : (2 : ℤ_[2]) ^ g ∣ α) (hαg' : ¬ (2 : ℤ_[2]) ^ (g + 1) ∣ α)
    (hqg : (2 : ℤ_[2]) ^ (g + 1) ∣ (q : ℤ_[2])) (hn : Even n) (hn₃ : 3 < n) {w : ℤ_[2]ˣ}
    (hw : (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g)
    (e : G ≃ₜ* presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)}) :
    (demushkinCharacter hG).toMonoidHom.range = (Subgroup.zpowers w).topologicalClosure :=
  range_demushkinCharacter_eq_of_equiv hG e fun _ ↦
    range_eq_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic_of_not_dvd hg hαg hαg' hqg hn
      hn₃ hw

/-- **A Demushkin group isomorphic to the even dyadic normal form with `α = 0` and `q = 0` has
orientation image `{±1}`**, for `n ≥ 2` even, `q = 0` being required only when the factor `x₃^q`
is present (`2 < n`): the relator is `x₁² (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)`, the endpoint `f = ∞`
of the even dyadic family. -/
theorem range_demushkinCharacter_eq_zpowers_neg_one_of_equiv_demushkinWordTwoEvenPadic (hα : α = 0)
    (hq : 2 < n → q = 0) (hn : Even n) (hn₁ : 1 < n)
    (e : G ≃ₜ* presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)}) :
    (demushkinCharacter hG).toMonoidHom.range = Subgroup.zpowers (-1) :=
  range_demushkinCharacter_eq_of_equiv hG e fun _ ↦
    range_eq_zpowers_neg_one_of_hasPrescriptionProperty_demushkinWordTwoEvenPadic hα hq hn hn₁

/-- **The image `{±1}` pins the endpoint of the even dyadic family.** If a Demushkin group is
isomorphic to `⟨x₁, …, xₙ ∣ x₁^{2+α} (x₁, x₂) x₃^q (x₃, x₄) ⋯ (x_{n-1}, x_n)⟩` with `4 ∣ α` and,
as soon as the factor `x₃^q` is present (`2 < n`), with `q = 0` or `q = 2^f` for some `f ≥ 2`, and
its canonical character has image `{±1}`, then `α = 0`, and `q = 0` as soon as the factor `x₃^q`
is present (at `n = 2` the relator `x₁^{2+α} (x₁, x₂)` does not involve `q`). The relator is then
`x₁² (x₁, x₂)(x₃, x₄) ⋯ (x_{n-1}, x_n)` (`TauCeti.demushkinWordTwoEvenPadic_zero_zero`, and
`TauCeti.demushkinWordTwoEvenPadic_two` at `n = 2`). -/
theorem IsDemushkin.eq_zero_and_eq_zero_of_range_demushkinCharacter_eq_zpowers_neg_one (hα : 4 ∣ α)
    (hq : 2 < n → q = 0 ∨ ∃ f, 2 ≤ f ∧ q = 2 ^ f) (hn : Even n) (hn₁ : 1 < n)
    (e : G ≃ₜ* presentedProP 2 (Fin n)
      {demushkinWordTwoEvenPadic (isProP_freeProP 2 (Fin n)) α q n (freeProPGen 2 n)})
    (hA : (demushkinCharacter hG).toMonoidHom.range = Subgroup.zpowers (-1)) :
    α = 0 ∧ (2 < n → q = 0) := by
  have hα₂ : 2 ∣ α := (Dvd.intro 2 (by norm_num)).trans hα
  have hq₂ : 2 < n → 2 ∣ q := fun hn₂ ↦ by
    rcases hq hn₂ with rfl | ⟨f, hf, rfl⟩
    exacts [dvd_zero 2, dvd_pow_self 2 (by omega)]
  obtain ⟨h₁, h₃, -⟩ :=
    demushkinCharacter_apply_equiv_symm_of_equiv_demushkinWordTwoEvenPadic hG hα₂ hq₂ hn hn₁ e
  -- Every value of the character is `±1`.
  have hmem : ∀ i, demushkinCharacter hG (e.symm (presentedProPGen 2 n _ i)) = 1 ∨
      demushkinCharacter hG (e.symm (presentedProPGen 2 n _ i)) = -1 := fun i ↦
    (Subgroup.mem_zpowers_neg_one_iff PadicInt.units_neg_one_ne_one).mp
      (by rw [← hA]; exact ⟨_, rfl⟩)
  refine ⟨?_, ?_⟩
  · rcases hmem 1 with h | h
    · -- `χ(x₂) = 1` would give `α = -2`, which is not divisible by `4`.
      exfalso
      rw [h, Units.val_one, one_mul] at h₁
      obtain ⟨c, hc⟩ := hα
      have h2 : (2 : ℤ_[2]) * 1 = 2 * (-2 * c) := by linear_combination -hc + h₁
      have h1 : (2 : ℤ_[2]) * (-c) = 1 := by
        linear_combination -(mul_left_cancel₀ two_ne_zero h2)
      exact PadicInt.p_nonunit (p := 2) (IsUnit.of_mul_eq_one (-c) h1)
    · rw [h, Units.val_neg, Units.val_one] at h₁
      linear_combination -h₁
  · intro hn₂
    replace h₃ := h₃ hn₂
    rcases hmem 3 with h | h
    · rw [h, Units.val_one, one_mul, sub_eq_self] at h₃
      exact_mod_cast h₃
    · -- `χ(x₄) = -1` would give `q = 2`, which is neither `0` nor `2^f` with `f ≥ 2`.
      exfalso
      rw [h, Units.val_neg, Units.val_one] at h₃
      have hq2 : q = 2 := by exact_mod_cast (by linear_combination h₃ : (q : ℤ_[2]) = 2)
      rcases hq hn₂ with rfl | ⟨f, hf, hqf⟩
      · exact absurd hq2 (by norm_num)
      · have := Nat.pow_le_pow_right (by norm_num : 0 < 2) hf
        omega

end Demushkin

end TauCeti
