/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.LowDegree
public import TauCeti.Topology.Algebra.Group.Generation

/-!
# Finiteness of `H¹` over a topologically finitely generated group

A continuous `1`-cocycle `f : G → M` satisfies `f (g * h) = g • f h + f g`, so its values on a
subgroup are determined by its values on a generating set of that subgroup, and by continuity a
cocycle into a discrete module is determined by its values on a topological generating set. Over a
topologically finitely generated group the continuous `1`-cocycles with values in a finite discrete
module therefore form a finite group, and so does `H¹(G, M)`.

## Main results

* `TauCeti.ContCohomology.Z1.eq_of_eqOn_of_topologicalClosure_closure_eq_top`: two continuous
  `1`-cocycles into a discrete module that agree on a topological generating set are equal.
* `TauCeti.IsTopologicallyFinitelyGenerated.finite_Z1` and
  `TauCeti.IsTopologicallyFinitelyGenerated.finite_H1`: over a topologically finitely generated
  group, `Z¹(G, M)` and `H¹(G, M)` are finite for every finite discrete `G`-module `M`.
-/

public section

namespace TauCeti

open ContCohomology

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  {M : Type*} [AddCommGroup M] [TopologicalSpace M] [DiscreteTopology M] [DistribMulAction G M]

/-- **A continuous `1`-cocycle is determined by its values on a topological generating set.** Two
continuous `1`-cocycles with values in a discrete module that agree on a set `s` generating a dense
subgroup are equal: the cocycle identity propagates the agreement to the subgroup generated by `s`,
and continuity propagates it to its closure. -/
theorem ContCohomology.Z1.eq_of_eqOn_of_topologicalClosure_closure_eq_top {s : Set G}
    (hs : (Subgroup.closure s).topologicalClosure = ⊤) {f f' : Z1 G M}
    (h : Set.EqOn (f : G → M) f' s) : f = f' := by
  have hf := mem_Z1_iff.1 f.2
  have hf' := mem_Z1_iff.1 f'.2
  -- a cocycle takes the value `x⁻¹ • -f x` at `x⁻¹`
  have hinv : ∀ (c : Z1 G M) (x : G), (c : G → M) x⁻¹ = x⁻¹ • -(c : G → M) x := fun c x ↦ by
    rw [← map_inv_of_mem_Z1 c.2 x, inv_smul_smul]
  have hagree : Set.EqOn (f : G → M) f' (Subgroup.closure s) := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem x hx => exact h hx
    | one => rw [map_one_of_mem_Z1 f.2, map_one_of_mem_Z1 f'.2]
    | mul x y _ _ hx hy => rw [hf.2 x y, hf'.2 x y, hx, hy]
    | inv x _ hx => rw [hinv f x, hinv f' x, hx]
  have hdense : Dense (Subgroup.closure s : Set G) := by
    rw [dense_iff_closure_eq, ← Subgroup.topologicalClosure_coe, hs, Subgroup.coe_top]
  exact Subtype.ext (hf.1.ext_on hdense hf'.1 hagree)

/-- **Finiteness of the continuous `1`-cocycles.** Over a topologically finitely generated group,
the continuous `1`-cocycles with values in a finite discrete module form a finite group: restriction
to a finite topological generating set is injective. -/
theorem IsTopologicallyFinitelyGenerated.finite_Z1 (hG : IsTopologicallyFinitelyGenerated G)
    [Finite M] : Finite (Z1 G M) := by
  obtain ⟨s, hs⟩ := isTopologicallyFinitelyGenerated_iff.1 hG
  refine Finite.of_injective (fun f : Z1 G M ↦ fun x : s ↦ (f : G → M) x) fun f f' h ↦ ?_
  exact Z1.eq_of_eqOn_of_topologicalClosure_closure_eq_top hs fun x hx ↦ congrFun h ⟨x, hx⟩

/-- **Finiteness of `H¹`.** Over a topologically finitely generated group, `H¹(G, M)` is finite for
every finite discrete `G`-module `M`. -/
theorem IsTopologicallyFinitelyGenerated.finite_H1 (hG : IsTopologicallyFinitelyGenerated G)
    [ContinuousSMul G M] [Finite M] : Finite (H1 G M) :=
  have := hG.finite_Z1 (M := M)
  Finite.of_surjective _ (QuotientAddGroup.mk'_surjective ((B1 G M).addSubgroupOf (Z1 G M)))

end TauCeti
