/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Orthogonal.TypeB.SpinCarrier.Basic
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot

/-!
# Generation of the type-B spin weight torus by root subgroups

The full-weight type-`Bₙ₊₁` spin carrier is defined from its positive and negative numbered
simple-root subgroups together with its split weight torus. This file proves that, in rank at
least three and over every commutative ring, the torus is already contained in the elementary
subgroup generated by those root subgroups.

The represented simple generators at each node form an `sl_2` triple by
`TauCeti.TypeBSpinCarrier.isSl2Triple_rep_rootGenerator`. The remaining concrete input is
supplied here: in rank at least three every row of the type-`B` Cartan matrix contains an entry
`-1`, so explicit Bezout coefficients make every simple root a primitive character of the weight
torus. The generic Kostant coroot-generation theorem then makes the torus redundant in the
pointwise generating family.

Rank two is excluded because the argument does not reach it: the long simple root of `B₂` has
Cartan row `(2, -2)`, whose values on the weight torus are the squares of units, so the coroot
values it produces are only the squares. The torus of the rank-two carrier does lie in its
elementary subgroup, by Chevalley's identity `h_α(u) = w_α(u) w_α(1)⁻¹`, but that identity is
not part of the generic theorem used here.

The conclusion concerns subgroups of the automorphism group of the base-changed admissible
lattice. Identifying these generated points with all points of the toral-closure group scheme is
a separate scheme-theoretic comparison.

## Main results

* `TauCeti.TypeBSpinCarrier.weightTorusSubgroup_le_elementarySubgroup`: in rank at least three,
  the weight torus lies in the elementary subgroup over every commutative ring.
* `TauCeti.TypeBSpinCarrier.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: in rank at
  least three, adjoining the weight torus to all numbered root subgroups gives exactly the
  elementary subgroup.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.

This file follows the formal template of
`TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.Generation`: the adjacent-node Bezout
certificate and the two specializations of the generic coroot-generation theorems are adapted
from it, with the type-`B` Cartan matrix and spin weights in place of the type-`D` data.
-/

public section

open scoped Matrix TensorProduct

universe v

namespace TauCeti.TypeBSpinCarrier

open TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (n : ℕ) (hn : 2 ≤ n)

/-- A node adjacent to `i`: the successor away from the terminal short node, and the predecessor
at the two terminal nodes. In rank at least three the Cartan entry at `(i, cartanNeighbor i)`
is `-1`. -/
private def cartanNeighbor (i : Fin (n + 1)) : Fin (n + 1) :=
  ⟨if (i : ℕ) + 1 < n then (i : ℕ) + 1 else (i : ℕ) - 1, by split_ifs <;> omega⟩

@[simp]
private theorem cartanNeighbor_val (i : Fin (n + 1)) :
    (cartanNeighbor n i : ℕ) = if (i : ℕ) + 1 < n then (i : ℕ) + 1 else (i : ℕ) - 1 := rfl

private def cartanBezout (i j : Fin (n + 1)) : ℤ :=
  if j = cartanNeighbor n i then -1 else 0

private theorem rootWeight_inr_eq_neg_inl (i : Fin (n + 1)) :
    rootWeight n (.inr i) = -rootWeight n (.inl i) := by
  rw [rootWeight_inr, rootWeight_inl]

include hn

private theorem cartan_sum_mul_bezout (i : Fin (n + 1)) :
    ∑ j, CartanMatrix.B (n + 1) i j * cartanBezout n i j = 1 := by
  classical
  rw [Finset.sum_eq_single (cartanNeighbor n i)]
  · have hentry : CartanMatrix.B (n + 1) i (cartanNeighbor n i) = -1 := by
      simp only [CartanMatrix.B, Matrix.of_apply, Fin.ext_iff, cartanNeighbor_val]
      split_ifs <;> omega
    simp [cartanBezout, hentry]
  · intro j _ hj
    simp [cartanBezout, hj]
  · simp

private theorem rootWeight_sum_mul_bezout (i : Fin (n + 1)) :
    ∑ j, rootWeight n (.inl i) j * cartanBezout n i j = 1 := by
  simpa only [rootWeight_inl] using cartan_sum_mul_bezout n hn i

/-- In rank at least three and over every commutative ring, the type-`B` full-spin weight torus
on the base-changed admissible lattice is contained in the elementary group generated by the
positive and negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup (lattice n).toAddSubgroup (latticeBasis n) (basisWeight n) A ≤
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A := by
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n) (rootWeight n)
    (lie_coroot_rootGenerator n) Sum.inl Sum.inr
    (isSl2Triple_rep_rootGenerator n) (rootWeight_inr_eq_neg_inl n)
    (cartanBezout n) (rootWeight_sum_mul_bezout n hn) A

/-- In rank at least three and over every commutative ring, adjoining the type-`B` full-spin
weight torus to all positive and negative numbered simple root subgroups does not enlarge their
elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n) Set.univ A =
      kostantElementarySubgroup (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
        (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
        (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
        (isNilpotent_rep_rootGenerator n) A := by
  exact kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
    (TauCeti.typeBSimpleRootGeneratorFamily (K := ℚ))
    (TauCeti.typeBSimpleCorootGenerator (K := ℚ)) (rep n)
    (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n)
    (isNilpotent_rep_rootGenerator n) (latticeBasis n) (basisWeight n)
    (isCartanWeightVector_latticeBasis n) (rootWeight n)
    (lie_coroot_rootGenerator n) Sum.inl Sum.inr
    (isSl2Triple_rep_rootGenerator n) (rootWeight_inr_eq_neg_inl n)
    (cartanBezout n) (rootWeight_sum_mul_bezout n hn) A

end TauCeti.TypeBSpinCarrier
