/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module
public import TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups
public import TauCeti.Topology.Algebra.ContinuousMonoidHom
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicUnits
import TauCeti.NumberTheory.Padics.PadicIntegers

/-!
# The standard orientations of the Demushkin normal forms

Each Demushkin normal form carries a marked continuous character to `ℤ_pˣ`, its **standard
orientation**, with the values that Labute's Theorem 4 tabulates on the normal-form basis:

* `q ≠ 2`, `n` even: `χ(x₂) = (1 - q)⁻¹` and `χ(x_i) = 1` otherwise;
* `q = 2`, `n` odd: `χ(x₁) = -1`, `χ(x₃) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise;
* `q = 2`, `n` even: `χ(x₂) = -(1 + α)⁻¹`, `χ(x₄) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise.

These characters exist because the values kill the relator: the commutators die in the
commutative group `ℤ_pˣ`, and the remaining factors are powers of generators sent to `1` or to
`-1` with even exponent. This file constructs the three characters on the presented pro-`p`
groups of the normal forms, records their values, and identifies their images with the closed
subgroups of `ℤ_pˣ` computed in `TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups`:
`1 + qℤ_p` in the first case, `{±1} × U^(f)` in the second, and in the third `{±1} × U^(f)` when
`2^f ∣ α` and the twisted subgroup `U^[v₂(α)]` otherwise.

The values are prescribed through the equations they satisfy, `u (1 - p^f) = 1` and
`v (1 + α) = -1`, so that no inverse has to be constructed to state a result. The characters are
defined for arbitrary values `u`, `v` (in `1 + pℤ_p` for the first family, so that the target of the
lift is pro-`p`); the equations enter only in the image computations.

## Main definitions

* `TauCeti.standardOrientationNeTwo`, `TauCeti.standardOrientationTwoOdd`,
  `TauCeti.standardOrientationTwoEven`: the standard orientations of the three normal forms.

## Main results

* `TauCeti.standardOrientationNeTwo_of` and the `_gen` lemmas, with their companions for the other
  two families: the values on the generators.
* `TauCeti.range_standardOrientationNeTwo`, `TauCeti.range_standardOrientationTwoOdd`,
  `TauCeti.range_standardOrientationTwoEven`: the image is the closed subgroup generated by the
  nontrivial values.
* `TauCeti.range_standardOrientationNeTwo_eq_unitsPrincipal`,
  `TauCeti.range_standardOrientationTwoOdd_eq_unitsPlusMinus`,
  `TauCeti.range_standardOrientationTwoEven_eq_unitsPlusMinus_of_dvd`,
  `TauCeti.exists_range_standardOrientationTwoEven_eq_of_not_dvd`: the image table.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132,
  Theorem 4 and its corollary.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., Chapter III, §9.
-/

public section

namespace TauCeti

variable {p : ℕ} [Fact p.Prime]

/-! ### The `q ≠ 2` normal form -/

section NeTwo

variable (q n : ℕ) (u : ℤ_[p]ˣ) (hu : u ∈ unitsPrincipal p 1)

/-- **The standard orientation of the `q ≠ 2` normal form**: the continuous character of the
pro-`p` group presented on `n` generators by `x₁^q (x₁, x₂) ⋯ (x_{n-1}, x_n)` with `χ(x₂) = u` and
`χ(x_i) = 1` otherwise, for a principal unit `u`. In the classification `u = (1 - q)⁻¹`. -/
noncomputable def standardOrientationNeTwo :
    presentedProP p (Fin n) {demushkinWordNeTwo q n (freeProPGen p n)} →ₜ* ℤ_[p]ˣ :=
  presentedProP.lift ((ContinuousMonoidHom.subgroupSubtype _).comp
    (freeProP.lift (isProP_unitsPrincipal p one_pos)
      fun i : Fin n ↦ if (i : ℕ) = 1 then ⟨u, hu⟩ else 1)) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordNeTwo_eq_one _ q n ?_
    rw [ContinuousMonoidHom.comp_toFun, freeProP.lift_freeProPGen]
    split_ifs <;> simp_all

/-- The value of the standard orientation of the `q ≠ 2` normal form on the generators. -/
@[simp]
theorem standardOrientationNeTwo_of (i : Fin n) :
    standardOrientationNeTwo q n u hu (presentedProP.of p _ i) = if (i : ℕ) = 1 then u else 1 := by
  rw [standardOrientationNeTwo, presentedProP.lift_of, ContinuousMonoidHom.comp_toFun,
    freeProP.lift_of]
  split_ifs <;> simp

/-- The standard orientation of the `q ≠ 2` normal form takes `x₂` to `u`. -/
theorem standardOrientationNeTwo_gen_one (hn : 1 < n) :
    standardOrientationNeTwo q n u hu (presentedProPGen p n _ 1) = u := by
  rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt p hn, presentedProP.mk_of,
    standardOrientationNeTwo_of]
  simp

/-- The standard orientation of the `q ≠ 2` normal form is trivial on every generator other than
`x₂`. -/
theorem standardOrientationNeTwo_gen_of_ne {i : ℕ} (hi : i ≠ 1) :
    standardOrientationNeTwo q n u hu (presentedProPGen p n _ i) = 1 := by
  rcases lt_or_ge i n with h | h
  · rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt p h, presentedProP.mk_of,
      standardOrientationNeTwo_of]
    simp [hi]
  · rw [presentedProPGen_of_le p n _ h, map_one]

/-- The image of the standard orientation of the `q ≠ 2` normal form is the closed subgroup
generated by `u`, as soon as the generator `x₂` exists. -/
theorem range_standardOrientationNeTwo (hn : 1 < n) :
    (standardOrientationNeTwo q n u hu).toMonoidHom.range =
      (Subgroup.zpowers u).topologicalClosure := by
  refine le_antisymm ((MonoidHom.range_le_iff_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (standardOrientationNeTwo q n u hu).continuous
    (Subgroup.isClosed_topologicalClosure _)).mpr ?_) (Subgroup.topologicalClosure_minimal _
    (Subgroup.zpowers_le.mpr ⟨_, standardOrientationNeTwo_gen_one q n u hu hn⟩)
    (ContinuousMonoidHom.isClosed_range _))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_coe, standardOrientationNeTwo_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_zpowers u)
  · exact one_mem _

/-- **The image of the standard orientation of the `q ≠ 2` normal form is `1 + qℤ_p`**: for
`q = p^f` with `f ≥ 1`, and `f ≥ 2` when `p = 2`, the character with `χ(x₂) = (1 - q)⁻¹` and
`χ(x_i) = 1` otherwise has image `U^(f)`. -/
theorem range_standardOrientationNeTwo_eq_unitsPrincipal (hn : 1 < n) {f : ℕ} (hf : 0 < f)
    (hf₂ : p = 2 → 2 ≤ f) (hu' : (u : ℤ_[p]) * (1 - (p : ℤ_[p]) ^ f) = 1) :
    (standardOrientationNeTwo q n u hu).toMonoidHom.range = unitsPrincipal p f := by
  rw [range_standardOrientationNeTwo q n u hu hn,
    topologicalClosure_zpowers_eq_unitsPrincipal_of_val_mul_one_sub_pow_eq_one hf hf₂ hu']

end NeTwo

/-! ### The `q = 2`, `n` odd normal form -/

section TwoOdd

variable (f n : ℕ) (u : ℤ_[2]ˣ)

/-- **The standard orientation of the `q = 2`, `n` odd normal form**: the continuous character of
the pro-`2` group presented on `n` generators by `x₁² x₂^{2^f} (x₂, x₃) ⋯ (x_{n-1}, x_n)` with
`χ(x₁) = -1`, `χ(x₃) = u` and `χ(x_i) = 1` otherwise. In the classification `u = (1 - 2^f)⁻¹`. -/
noncomputable def standardOrientationTwoOdd :
    presentedProP 2 (Fin n) {demushkinWordTwoOdd f n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ :=
  presentedProP.lift (freeProP.lift isProP_units_padicInt_two
      fun i : Fin n ↦ if (i : ℕ) = 0 then -1 else if (i : ℕ) = 2 then u else 1) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordTwoOdd_eq_one _ f n ?_ ?_ <;>
      rw [freeProP.lift_freeProPGen] <;> split_ifs <;> simp_all

/-- The value of the standard orientation of the `q = 2`, `n` odd normal form on the
generators. -/
@[simp]
theorem standardOrientationTwoOdd_of (i : Fin n) :
    standardOrientationTwoOdd f n u (presentedProP.of 2 _ i) =
      if (i : ℕ) = 0 then -1 else if (i : ℕ) = 2 then u else 1 := by
  rw [standardOrientationTwoOdd, presentedProP.lift_of, freeProP.lift_of]

/-- The standard orientation of the `q = 2`, `n` odd normal form takes `x₁` to `-1`. -/
theorem standardOrientationTwoOdd_gen_zero (hn : 0 < n) :
    standardOrientationTwoOdd f n u (presentedProPGen 2 n _ 0) = -1 := by
  rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 hn, presentedProP.mk_of,
    standardOrientationTwoOdd_of]
  simp

/-- The standard orientation of the `q = 2`, `n` odd normal form takes `x₃` to `u`. -/
theorem standardOrientationTwoOdd_gen_two (hn : 2 < n) :
    standardOrientationTwoOdd f n u (presentedProPGen 2 n _ 2) = u := by
  rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 hn, presentedProP.mk_of,
    standardOrientationTwoOdd_of]
  simp

/-- The standard orientation of the `q = 2`, `n` odd normal form is trivial on every generator
other than `x₁` and `x₃`. -/
theorem standardOrientationTwoOdd_gen_of_ne {i : ℕ} (hi₀ : i ≠ 0) (hi₂ : i ≠ 2) :
    standardOrientationTwoOdd f n u (presentedProPGen 2 n _ i) = 1 := by
  rcases lt_or_ge i n with h | h
  · rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 h, presentedProP.mk_of,
      standardOrientationTwoOdd_of]
    simp [hi₀, hi₂]
  · rw [presentedProPGen_of_le 2 n _ h, map_one]

/-- The image of the standard orientation of the `q = 2`, `n` odd normal form is the closed
subgroup generated by `-1` and `u`, as soon as the generator `x₃` exists. -/
theorem range_standardOrientationTwoOdd (hn : 2 < n) :
    (standardOrientationTwoOdd f n u).toMonoidHom.range =
      (Subgroup.zpowers (-1) ⊔ Subgroup.zpowers u).topologicalClosure := by
  refine le_antisymm ((MonoidHom.range_le_iff_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (standardOrientationTwoOdd f n u).continuous
    (Subgroup.isClosed_topologicalClosure _)).mpr ?_) (Subgroup.topologicalClosure_minimal _
    (sup_le (Subgroup.zpowers_le.mpr ⟨_, standardOrientationTwoOdd_gen_zero f n u (by omega)⟩)
      (Subgroup.zpowers_le.mpr ⟨_, standardOrientationTwoOdd_gen_two f n u hn⟩))
    (ContinuousMonoidHom.isClosed_range _))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_coe, standardOrientationTwoOdd_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
  · exact one_mem _

/-- **The image of the standard orientation of the `q = 2`, `n` odd normal form is
`{±1} × U^(f)`**: for `f ≥ 2`, the character with `χ(x₁) = -1`, `χ(x₃) = (1 - 2^f)⁻¹` and
`χ(x_i) = 1` otherwise has image `V^(f)`. -/
theorem range_standardOrientationTwoOdd_eq_unitsPlusMinus (hn : 2 < n) (hf : 2 ≤ f)
    (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1) :
    (standardOrientationTwoOdd f n u).toMonoidHom.range = unitsPlusMinus f := by
  rw [range_standardOrientationTwoOdd f n u hn,
    topologicalClosure_zpowers_neg_one_sup_zpowers_eq_unitsPlusMinus hf hu]

end TwoOdd

/-! ### The `q = 2`, `n` even normal form -/

section TwoEven

variable (a f n : ℕ) (v u : ℤ_[2]ˣ)

/-- **The standard orientation of the `q = 2`, `n` even normal form**: the continuous character
of the pro-`2` group presented on `n` generators by
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` with `χ(x₂) = v`, `χ(x₄) = u` and
`χ(x_i) = 1` otherwise. In the classification `v = -(1 + a)⁻¹` and `u = (1 - 2^f)⁻¹`. -/
noncomputable def standardOrientationTwoEven :
    presentedProP 2 (Fin n) {demushkinWordTwoEven a f n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ :=
  presentedProP.lift (freeProP.lift isProP_units_padicInt_two
      fun i : Fin n ↦ if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordTwoEven_eq_one _ a f n ?_ ?_ <;>
      rw [freeProP.lift_freeProPGen] <;> split_ifs <;> simp_all

/-- The value of the standard orientation of the `q = 2`, `n` even normal form on the
generators. -/
@[simp]
theorem standardOrientationTwoEven_of (i : Fin n) :
    standardOrientationTwoEven a f n v u (presentedProP.of 2 _ i) =
      if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1 := by
  rw [standardOrientationTwoEven, presentedProP.lift_of, freeProP.lift_of]

/-- The standard orientation of the `q = 2`, `n` even normal form takes `x₂` to `v`. -/
theorem standardOrientationTwoEven_gen_one (hn : 1 < n) :
    standardOrientationTwoEven a f n v u (presentedProPGen 2 n _ 1) = v := by
  rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 hn, presentedProP.mk_of,
    standardOrientationTwoEven_of]
  simp

/-- The standard orientation of the `q = 2`, `n` even normal form takes `x₄` to `u`. -/
theorem standardOrientationTwoEven_gen_three (hn : 3 < n) :
    standardOrientationTwoEven a f n v u (presentedProPGen 2 n _ 3) = u := by
  rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 hn, presentedProP.mk_of,
    standardOrientationTwoEven_of]
  simp

/-- The standard orientation of the `q = 2`, `n` even normal form is trivial on every generator
other than `x₂` and `x₄`. -/
theorem standardOrientationTwoEven_gen_of_ne {i : ℕ} (hi₁ : i ≠ 1) (hi₃ : i ≠ 3) :
    standardOrientationTwoEven a f n v u (presentedProPGen 2 n _ i) = 1 := by
  rcases lt_or_ge i n with h | h
  · rw [← presentedProP.mk_freeProPGen, freeProPGen_of_lt 2 h, presentedProP.mk_of,
      standardOrientationTwoEven_of]
    simp [hi₁, hi₃]
  · rw [presentedProPGen_of_le 2 n _ h, map_one]

/-- The image of the standard orientation of the `q = 2`, `n` even normal form is the closed
subgroup generated by `v` and `u`, as soon as the generator `x₄` exists. -/
theorem range_standardOrientationTwoEven (hn : 3 < n) :
    (standardOrientationTwoEven a f n v u).toMonoidHom.range =
      (Subgroup.zpowers v ⊔ Subgroup.zpowers u).topologicalClosure := by
  refine le_antisymm ((MonoidHom.range_le_iff_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (standardOrientationTwoEven a f n v u).continuous
    (Subgroup.isClosed_topologicalClosure _)).mpr ?_) (Subgroup.topologicalClosure_minimal _
    (sup_le
      (Subgroup.zpowers_le.mpr ⟨_, standardOrientationTwoEven_gen_one a f n v u (by omega)⟩)
      (Subgroup.zpowers_le.mpr ⟨_, standardOrientationTwoEven_gen_three a f n v u hn⟩))
    (ContinuousMonoidHom.isClosed_range _))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_coe, standardOrientationTwoEven_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
  · exact one_mem _

/-- **The image of the standard orientation of the `q = 2`, `n` even normal form when
`2^f ∣ α`** is `{±1} × U^(f)`: for `f ≥ 2`, the character with `χ(x₂) = -(1 + a)⁻¹`,
`χ(x₄) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise has image `V^(f)`. This includes `a = 0`. -/
theorem range_standardOrientationTwoEven_eq_unitsPlusMinus_of_dvd (hn : 3 < n) (hf : 2 ≤ f)
    (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1) (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1)
    (ha : (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) :
    (standardOrientationTwoEven a f n v u).toMonoidHom.range = unitsPlusMinus f := by
  rw [range_standardOrientationTwoEven a f n v u hn,
    topologicalClosure_zpowers_sup_zpowers_eq_unitsPlusMinus_of_dvd hf hv hu ha]

/-- **The image of the standard orientation of the `q = 2`, `n` even normal form when
`4 ∣ α` but `2^f ∤ α`** is the twisted subgroup `U^[g]` generated by `-1 + 2^g`, where
`g = v₂(α)` satisfies `2 ≤ g < f`. -/
theorem exists_range_standardOrientationTwoEven_eq_of_not_dvd (hn : 3 < n)
    (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1) (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1)
    (ha₄ : 4 ∣ (a : ℤ_[2])) (ha : ¬ (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) :
    ∃ (g : ℕ) (w : ℤ_[2]ˣ), 2 ≤ g ∧ g < f ∧
      (2 : ℤ_[2]) ^ g ∣ (a : ℤ_[2]) ∧ ¬ (2 : ℤ_[2]) ^ (g + 1) ∣ (a : ℤ_[2]) ∧
      (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g ∧
      (standardOrientationTwoEven a f n v u).toMonoidHom.range =
        (Subgroup.zpowers w).topologicalClosure := by
  obtain ⟨g, w, hg, hgf, hga, hga', hw, hrange⟩ :=
    exists_topologicalClosure_zpowers_sup_zpowers_eq_of_not_dvd hv hu ha₄ ha
  exact ⟨g, w, hg, hgf, hga, hga', hw, by
    rw [range_standardOrientationTwoEven a f n v u hn, hrange]⟩

end TwoEven

end TauCeti
