/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module
public import TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups
public import TauCeti.Topology.Algebra.ContinuousMonoidHom
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicUnits
import TauCeti.NumberTheory.Padics.PadicIntegers

/-!
# The orientations of the Demushkin normal forms

Each Demushkin normal form carries a marked continuous character to `ℤ_pˣ`, its **standard
orientation**, with the values that Labute's Theorem 4 tabulates on the normal-form basis:

* `q ≠ 2`, `n` even: `χ(x₂) = (1 - q)⁻¹` and `χ(x_i) = 1` otherwise;
* `q = 2`, `n` odd: `χ(x₁) = -1`, `χ(x₃) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise;
* `q = 2`, `n` even: `χ(x₂) = -(1 + α)⁻¹`, `χ(x₄) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise.

These characters exist because the values kill the relator: the commutators die in the
commutative group `ℤ_pˣ`, and the remaining factors are powers of generators sent to `1` or to
`-1` with even exponent. This file constructs, on the presented pro-`p` group of each normal form,
the continuous characters of this shape with the marked values left as parameters:
`orientationNeTwo q n u` with `χ(x₂) = u`, `orientationTwoOdd f n u` with `χ(x₁) = -1`,
`χ(x₃) = u`, and `orientationTwoEven a f n v u` with `χ(x₂) = v`, `χ(x₄) = u`, each trivial on
the other generators. The standard orientation is the member of the family with the tabulated
values, prescribed through the equations they satisfy, `u (1 - q) = 1` for `q = p^f` and
`v (1 + α) = -1`, so that no inverse has to be constructed to state a result. The characters
themselves are defined for arbitrary `u`, `v` (with `u` in `1 + pℤ_p` for the first family, so
that the target of the lift is pro-`p`); the equations enter only in the image computations.

The image of each character is the closed subgroup of `ℤ_pˣ` generated by its marked values, as
soon as the marked generators exist: `1 < n` for the first family, `2 < n` for the second and
`3 < n` for the third, which the classification always provides (`n ≥ 2` even, `n ≥ 3` odd,
`n ≥ 4` even). Under these rank bounds and the equations on `u`, `v`, the images are the closed
subgroups computed in `TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups`: `1 + qℤ_p` in the
first case, `{±1} × U^(f)` in the second, and in the third `{±1} × U^(f)` when `2^f ∣ α` and the
twisted subgroup `U^[v₂(α)]` otherwise.

## Main definitions

* `TauCeti.orientationNeTwo`, `TauCeti.orientationTwoOdd`, `TauCeti.orientationTwoEven`: the
  characters of the three normal forms with the shape of the standard orientation and marked
  values `u`, resp. `-1` and `u`, resp. `v` and `u`.

## Main results

* `TauCeti.orientationNeTwo_of` and the `_presentedProPGen_` lemmas, with their companions for
  the other two families: the values on the generators.
* `TauCeti.range_orientationNeTwo`, `TauCeti.range_orientationTwoOdd`,
  `TauCeti.range_orientationTwoEven`: for `1 < n`, resp. `2 < n`, resp. `3 < n`, the image is
  the closed subgroup generated by the marked values.
* `TauCeti.range_orientationNeTwo_eq_unitsPrincipal`,
  `TauCeti.range_orientationTwoOdd_eq_unitsPlusMinus`,
  `TauCeti.range_orientationTwoEven_eq_unitsPlusMinus_of_dvd`,
  `TauCeti.exists_range_orientationTwoEven_eq_of_not_dvd`: the image table of the standard
  orientations, under the same rank bounds.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132,
  Theorem 4 and its corollary.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., Chapter III, §9.
-/

public section

namespace TauCeti

variable {p : ℕ} [Fact p.Prime]

/-! ### The `q ≠ 2` normal form -/

section NeTwo

variable (q n : ℕ) (u : ℤ_[p]ˣ) (hu : u ∈ unitsPrincipal p 1)

/-- **The orientation of the `q ≠ 2` normal form with marked value `u`**: the continuous
character of the pro-`p` group presented on `n` generators by `x₁^q (x₁, x₂) ⋯ (x_{n-1}, x_n)` with
`χ(x₂) = u` and `χ(x_i) = 1` otherwise, for a principal unit `u`. The standard orientation of the
classification is the case `u = (1 - q)⁻¹`. -/
noncomputable def orientationNeTwo :
    presentedProP p (Fin n) {demushkinWordNeTwo q n (freeProPGen p n)} →ₜ* ℤ_[p]ˣ :=
  presentedProP.lift ((ContinuousMonoidHom.subgroupSubtype _).comp
    (freeProP.lift (isProP_unitsPrincipal p one_pos)
      fun i : Fin n ↦ if (i : ℕ) = 1 then ⟨u, hu⟩ else 1)) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordNeTwo_eq_one _ q n ?_
    rw [ContinuousMonoidHom.comp_toFun, freeProP.lift_freeProPGen]
    split_ifs <;> simp_all

/-- The value of the orientation of the `q ≠ 2` normal form on the generators. -/
@[simp]
theorem orientationNeTwo_of (i : Fin n) :
    orientationNeTwo q n u hu (presentedProP.of p _ i) = if (i : ℕ) = 1 then u else 1 := by
  rw [orientationNeTwo, presentedProP.lift_of, ContinuousMonoidHom.comp_toFun,
    freeProP.lift_of]
  split_ifs <;> simp

/-- The orientation of the `q ≠ 2` normal form takes `x₂` to its marked value `u`. -/
theorem orientationNeTwo_presentedProPGen_one (hn : 1 < n) :
    orientationNeTwo q n u hu (presentedProPGen p n _ 1) = u := by
  rw [presentedProPGen_of_lt p n _ hn, orientationNeTwo_of]
  simp

/-- The orientation of the `q ≠ 2` normal form is trivial on every generator other than `x₂`. -/
@[simp]
theorem orientationNeTwo_presentedProPGen_of_ne {i : ℕ} (hi : i ≠ 1) :
    orientationNeTwo q n u hu (presentedProPGen p n _ i) = 1 := by
  rw [map_presentedProPGen]
  split_ifs <;> simp [hi]

/-- The image of the orientation of the `q ≠ 2` normal form is the closed subgroup generated by
its marked value `u`, as soon as the generator `x₂` exists. -/
theorem range_orientationNeTwo (hn : 1 < n) :
    (orientationNeTwo q n u hu).toMonoidHom.range =
      (Subgroup.zpowers u).topologicalClosure := by
  refine MonoidHom.range_eq_topologicalClosure_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (orientationNeTwo q n u hu).continuous ?_
    (Subgroup.zpowers_le.mpr ⟨_, orientationNeTwo_presentedProPGen_one q n u hu hn⟩)
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, orientationNeTwo_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_zpowers u)
  · exact one_mem _

/-- **The image of the standard orientation of the `q ≠ 2` normal form is `1 + qℤ_p`**: for
`1 < n` and `q = p^f` with `f ≥ 1`, and `f ≥ 2` when `p = 2`, the character with
`χ(x₂) = (1 - q)⁻¹` and `χ(x_i) = 1` otherwise has image `U^(f) = 1 + qℤ_p`. -/
theorem range_orientationNeTwo_eq_unitsPrincipal (hn : 1 < n) {f : ℕ} (hq : q = p ^ f)
    (hf : 0 < f) (hf₂ : p = 2 → 2 ≤ f) (hu' : (u : ℤ_[p]) * (1 - (q : ℤ_[p])) = 1) :
    (orientationNeTwo q n u hu).toMonoidHom.range = unitsPrincipal p f := by
  subst hq
  push_cast at hu'
  rw [range_orientationNeTwo _ n u hu hn,
    topologicalClosure_zpowers_eq_unitsPrincipal_of_val_mul_one_sub_pow_eq_one hf hf₂ hu']

end NeTwo

/-! ### The `q = 2`, `n` odd normal form -/

section TwoOdd

variable (f n : ℕ) (u : ℤ_[2]ˣ)

/-- **The orientation of the `q = 2`, `n` odd normal form with marked value `u`**: the continuous
character of the pro-`2` group presented on `n` generators by
`x₁² x₂^{2^f} (x₂, x₃) ⋯ (x_{n-1}, x_n)` with `χ(x₁) = -1`, `χ(x₃) = u` and `χ(x_i) = 1` otherwise.
The standard orientation of the classification is the case `u = (1 - 2^f)⁻¹`. -/
noncomputable def orientationTwoOdd :
    presentedProP 2 (Fin n) {demushkinWordTwoOdd f n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ :=
  presentedProP.lift (freeProP.lift isProP_units_padicInt_two
      fun i : Fin n ↦ if (i : ℕ) = 0 then -1 else if (i : ℕ) = 2 then u else 1) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordTwoOdd_eq_one _ f n ?_ ?_ <;>
      rw [freeProP.lift_freeProPGen] <;> split_ifs <;> simp_all

/-- The value of the orientation of the `q = 2`, `n` odd normal form on the generators. -/
@[simp]
theorem orientationTwoOdd_of (i : Fin n) :
    orientationTwoOdd f n u (presentedProP.of 2 _ i) =
      if (i : ℕ) = 0 then -1 else if (i : ℕ) = 2 then u else 1 := by
  rw [orientationTwoOdd, presentedProP.lift_of, freeProP.lift_of]

/-- The orientation of the `q = 2`, `n` odd normal form takes `x₁` to `-1`. -/
theorem orientationTwoOdd_presentedProPGen_zero (hn : 0 < n) :
    orientationTwoOdd f n u (presentedProPGen 2 n _ 0) = -1 := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoOdd_of]
  simp

/-- The orientation of the `q = 2`, `n` odd normal form takes `x₃` to its marked value `u`. -/
theorem orientationTwoOdd_presentedProPGen_two (hn : 2 < n) :
    orientationTwoOdd f n u (presentedProPGen 2 n _ 2) = u := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoOdd_of]
  simp

/-- The orientation of the `q = 2`, `n` odd normal form is trivial on every generator other than
`x₁` and `x₃`. -/
@[simp]
theorem orientationTwoOdd_presentedProPGen_of_ne {i : ℕ} (hi₀ : i ≠ 0) (hi₂ : i ≠ 2) :
    orientationTwoOdd f n u (presentedProPGen 2 n _ i) = 1 := by
  rw [map_presentedProPGen]
  split_ifs <;> simp [hi₀, hi₂]

/-- The image of the orientation of the `q = 2`, `n` odd normal form is the closed subgroup
generated by `-1` and its marked value `u`, as soon as the generator `x₃` exists. -/
theorem range_orientationTwoOdd (hn : 2 < n) :
    (orientationTwoOdd f n u).toMonoidHom.range =
      (Subgroup.zpowers (-1) ⊔ Subgroup.zpowers u).topologicalClosure := by
  refine MonoidHom.range_eq_topologicalClosure_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (orientationTwoOdd f n u).continuous ?_
    (sup_le
      (Subgroup.zpowers_le.mpr
        ⟨_, orientationTwoOdd_presentedProPGen_zero f n u (by omega)⟩)
      (Subgroup.zpowers_le.mpr ⟨_, orientationTwoOdd_presentedProPGen_two f n u hn⟩))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, orientationTwoOdd_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
  · exact one_mem _

/-- **The image of the standard orientation of the `q = 2`, `n` odd normal form is
`{±1} × U^(f)`**: for `2 < n` and `f ≥ 2`, the character with `χ(x₁) = -1`, `χ(x₃) = (1 - 2^f)⁻¹`
and `χ(x_i) = 1` otherwise has image `V^(f)`. -/
theorem range_orientationTwoOdd_eq_unitsPlusMinus (hn : 2 < n) (hf : 2 ≤ f)
    (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1) :
    (orientationTwoOdd f n u).toMonoidHom.range = unitsPlusMinus f := by
  rw [range_orientationTwoOdd f n u hn,
    topologicalClosure_zpowers_neg_one_sup_zpowers_eq_unitsPlusMinus hf hu]

end TwoOdd

/-! ### The `q = 2`, `n` even normal form -/

section TwoEven

variable (a f n : ℕ) (v u : ℤ_[2]ˣ)

/-- **The orientation of the `q = 2`, `n` even normal form with marked values `v`, `u`**: the
continuous character of the pro-`2` group presented on `n` generators by
`x₁^{2+a} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{n-1}, x_n)` with `χ(x₂) = v`, `χ(x₄) = u` and
`χ(x_i) = 1` otherwise. The standard orientation of the classification is the case
`v = -(1 + a)⁻¹`, `u = (1 - 2^f)⁻¹`. -/
noncomputable def orientationTwoEven :
    presentedProP 2 (Fin n) {demushkinWordTwoEven a f n (freeProPGen 2 n)} →ₜ* ℤ_[2]ˣ :=
  presentedProP.lift (freeProP.lift isProP_units_padicInt_two
      fun i : Fin n ↦ if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1) fun r hr ↦ by
    rw [Set.mem_singleton_iff.mp hr]
    refine map_demushkinWordTwoEven_eq_one _ a f n ?_ ?_ <;>
      rw [freeProP.lift_freeProPGen] <;> split_ifs <;> simp_all

/-- The value of the orientation of the `q = 2`, `n` even normal form on the generators. -/
@[simp]
theorem orientationTwoEven_of (i : Fin n) :
    orientationTwoEven a f n v u (presentedProP.of 2 _ i) =
      if (i : ℕ) = 1 then v else if (i : ℕ) = 3 then u else 1 := by
  rw [orientationTwoEven, presentedProP.lift_of, freeProP.lift_of]

/-- The orientation of the `q = 2`, `n` even normal form takes `x₂` to its marked value `v`. -/
theorem orientationTwoEven_presentedProPGen_one (hn : 1 < n) :
    orientationTwoEven a f n v u (presentedProPGen 2 n _ 1) = v := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoEven_of]
  simp

/-- The orientation of the `q = 2`, `n` even normal form takes `x₄` to its marked value `u`. -/
theorem orientationTwoEven_presentedProPGen_three (hn : 3 < n) :
    orientationTwoEven a f n v u (presentedProPGen 2 n _ 3) = u := by
  rw [presentedProPGen_of_lt 2 n _ hn, orientationTwoEven_of]
  simp

/-- The orientation of the `q = 2`, `n` even normal form is trivial on every generator other than
`x₂` and `x₄`. -/
@[simp]
theorem orientationTwoEven_presentedProPGen_of_ne {i : ℕ} (hi₁ : i ≠ 1) (hi₃ : i ≠ 3) :
    orientationTwoEven a f n v u (presentedProPGen 2 n _ i) = 1 := by
  rw [map_presentedProPGen]
  split_ifs <;> simp [hi₁, hi₃]

/-- The image of the orientation of the `q = 2`, `n` even normal form is the closed subgroup
generated by its marked values `v` and `u`, as soon as the generator `x₄` exists. -/
theorem range_orientationTwoEven (hn : 3 < n) :
    (orientationTwoEven a f n v u).toMonoidHom.range =
      (Subgroup.zpowers v ⊔ Subgroup.zpowers u).topologicalClosure := by
  refine MonoidHom.range_eq_topologicalClosure_of_topologicalClosure_closure_eq_top
    presentedProP.topologicalClosure_closure_range_of_eq_top
    (orientationTwoEven a f n v u).continuous ?_
    (sup_le
      (Subgroup.zpowers_le.mpr
        ⟨_, orientationTwoEven_presentedProPGen_one a f n v u (by omega)⟩)
      (Subgroup.zpowers_le.mpr
        ⟨_, orientationTwoEven_presentedProPGen_three a f n v u hn⟩))
  rintro _ ⟨i, rfl⟩
  rw [ContinuousMonoidHom.coe_toMonoidHom, MonoidHom.coe_ofClass, orientationTwoEven_of]
  split_ifs
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_left (Subgroup.mem_zpowers _))
  · exact Subgroup.le_topologicalClosure _ (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
  · exact one_mem _

/-- **The image of the standard orientation of the `q = 2`, `n` even normal form when
`2^f ∣ α`** is `{±1} × U^(f)`: for `3 < n` and `f ≥ 2`, the character with `χ(x₂) = -(1 + a)⁻¹`,
`χ(x₄) = (1 - 2^f)⁻¹` and `χ(x_i) = 1` otherwise has image `V^(f)`. This includes `a = 0`. -/
theorem range_orientationTwoEven_eq_unitsPlusMinus_of_dvd (hn : 3 < n) (hf : 2 ≤ f)
    (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1) (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1)
    (ha : (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) :
    (orientationTwoEven a f n v u).toMonoidHom.range = unitsPlusMinus f := by
  rw [range_orientationTwoEven a f n v u hn,
    topologicalClosure_zpowers_sup_zpowers_eq_unitsPlusMinus_of_dvd hf hv hu ha]

/-- **The image of the standard orientation of the `q = 2`, `n` even normal form when
`4 ∣ α` but `2^f ∤ α`** is the twisted subgroup `U^[g]` generated by `-1 + 2^g`, where
`g = v₂(α)` satisfies `2 ≤ g < f`, for `3 < n`. -/
theorem exists_range_orientationTwoEven_eq_of_not_dvd (hn : 3 < n)
    (hv : (v : ℤ_[2]) * (1 + (a : ℤ_[2])) = -1) (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1)
    (ha₄ : 4 ∣ (a : ℤ_[2])) (ha : ¬ (2 : ℤ_[2]) ^ f ∣ (a : ℤ_[2])) :
    ∃ (g : ℕ) (w : ℤ_[2]ˣ), 2 ≤ g ∧ g < f ∧
      (2 : ℤ_[2]) ^ g ∣ (a : ℤ_[2]) ∧ ¬ (2 : ℤ_[2]) ^ (g + 1) ∣ (a : ℤ_[2]) ∧
      (w : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g ∧
      (orientationTwoEven a f n v u).toMonoidHom.range =
        (Subgroup.zpowers w).topologicalClosure := by
  obtain ⟨g, w, hg, hgf, hga, hga', hw, hrange⟩ :=
    exists_topologicalClosure_zpowers_sup_zpowers_eq_of_not_dvd hv hu ha₄ ha
  exact ⟨g, w, hg, hgf, hga, hga', hw, by
    rw [range_orientationTwoEven a f n v u hn, hrange]⟩

end TwoEven

end TauCeti
