/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Products
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Limits
public import Mathlib.LinearAlgebra.Dimension.Constructions
public import Mathlib.LinearAlgebra.FreeModule.StrongRankCondition
public import TauCeti.Algebra.Category.ModuleCat.Sheaf.FinitePresentation
public import TauCeti.Algebra.Category.ModuleCat.Sheaf.LocallyFree
public import TauCeti.Algebra.Category.ModuleCat.Sheaf.Quasicoherent.Refinement
public import TauCeti.Algebra.Category.ModuleCat.Sheaf.TensorProduct.Dual
public import TauCeti.CategoryTheory.Monoidal.Closed.Basic
public import TauCeti.CategoryTheory.Sites.CoversTop

/-!
# Finite locally free sheaves have finite local bases

Let `R` be a sheaf of commutative rings on a small site with pullbacks. A sheaf of `R`-modules
is finite locally free if it is locally free and finitely presented
(`SheafOfModules.isFiniteLocallyFree`). Local freeness alone provides local bases whose index
types may be infinite and vary from chart to chart; finite presentation provides finitely many
local generators on possibly different charts. This file shows that the two conditions together
are equivalent to the existence of locally free data with finite local bases
(`SheafOfModules.isFiniteLocallyFree_iff_exists_isLocallyFreeData_isFiniteType`), the
form in which finite local freeness is used to reduce statements about finite locally free
sheaves to finite free sheaves.

The proof passes to a common refinement of the two covers, on which the sheaf is at once free
on some index type `I` and generated by finitely many sections. If `I` is finite there is nothing
to do. Otherwise the free sheaf on `I` receives an epimorphism from a finite free sheaf, and the
degenerate case is that the sheaf of rings vanishes: an epimorphism `free J ⟶ free K` between
finite free sheaves with `|J| < |K|` dualizes to a monomorphism `free K ⟶ free J`, whose sections
over each object `W` give an injective `R(W)`-linear map `R(W)^K → R(W)^J`, so that `R(W)` is the
zero ring by the strong rank condition
(`TauCeti.SheafOfModules.subsingleton_of_epi_free_of_card_lt`). All sheaves of modules over a
vanishing sheaf of rings are zero, and the zero sheaf is free on the empty type.

## Main declarations

* `TauCeti.SheafOfModules.evaluationFreeIso`: the sections of `free I` over `W`, for finite `I`,
  are the `I`-tuples of sections of `R` over `W`;
* `TauCeti.SheafOfModules.subsingleton_of_epi_free_of_card_lt`: an epimorphism `free J ⟶ free K`
  with `|J| < |K|` forces the sheaf of rings to vanish;
* `TauCeti.SheafOfModules.isZero_of_forall_subsingleton`: sheaves of modules over a vanishing
  sheaf of rings are zero;
* `SheafOfModules.GeneratingSections.exists_isIso_π_isFiniteType`: a sheaf of modules that is
  free and of finite type is free on a finite type;
* `SheafOfModules.IsLocallyFree.exists_isLocallyFreeData_isFiniteType` and
  `SheafOfModules.isFiniteLocallyFree_iff_exists_isLocallyFreeData_isFiniteType`: the
  characterization of finite locally free sheaves by finite local bases.

## References

* [The Stacks Project, Tag 01C6](https://stacks.math.columbia.edu/tag/01C6)
-/

public section

open CategoryTheory Limits MonoidalCategory

namespace TauCeti

universe u v v₁ u₁

noncomputable section

namespace SheafOfModules

open _root_.SheafOfModules

section Zero

variable {C : Type u₁} [Category.{v₁} C] {J : GrothendieckTopology C} {S : Sheaf J RingCat.{u}}

/-- Every sheaf of modules over a sheaf of rings all of whose rings of sections are trivial is a
zero object. -/
theorem isZero_of_forall_subsingleton (hS : ∀ W, Subsingleton (S.obj.obj W))
    (N : SheafOfModules.{v} S) : IsZero N := by
  rw [IsZero.iff_id_eq_zero]
  apply SheafOfModules.hom_ext
  ext W x
  have := hS W
  have := Module.subsingleton (S.obj.obj W) (N.val.obj W)
  exact Subsingleton.elim _ _

end Zero

variable {C : Type u} [SmallCategory C] {J : GrothendieckTopology C}
variable [J.HasSheafCompose (forget₂ CommRingCat RingCat.{u})]
variable [HasWeakSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
variable {R : Sheaf J CommRingCat.{u}}

section Free

/-- The sections over `W` of the free sheaf of modules on a finite type `I` are the `I`-indexed
tuples of sections of the sheaf of rings over `W`: `free I` is the product of `I` copies of the
unit, and evaluation at `W` preserves products. -/
def evaluationFreeIso (I : Type u) [Finite I] (W : Cᵒᵖ) :
    (evaluation (ringCatSheaf R) W).obj (free I) ≅
      ModuleCat.of ((ringCatSheaf R).obj.obj W) (I → (ringCatSheaf R).obj.obj W) :=
  (evaluation (ringCatSheaf R) W).mapIso
      ((biproductIsoFree (R := R) I).symm ≪≫ biproduct.isoProduct _) ≪≫
    PreservesProduct.iso (evaluation (ringCatSheaf R) W) _ ≪≫ ModuleCat.piIsoPi _

/-- The `i`-th coordinate of a section of `free I` under `evaluationFreeIso` is its image under
the `i`-th projection `free I ⟶ R` of the biproduct decomposition of `free I`. -/
@[reassoc (attr := simp)]
theorem evaluationFreeIso_hom_comp_proj (I : Type u) [Finite I] (W : Cᵒᵖ) (i : I) :
    (evaluationFreeIso (R := R) I W).hom ≫ ModuleCat.ofHom (LinearMap.proj i) =
      (evaluation (ringCatSheaf R) W).map
        ((biproductIsoFree (R := R) I).inv ≫ biproduct.π _ i) := by
  -- The last factor of `evaluationFreeIso` lands in the module of `I`-tuples of sections of the
  -- unit over `W`, which is the module of `I`-tuples of sections of `R` only after unfolding
  -- `evaluation`; the composite is therefore spelled out in the former form before rewriting.
  change ((evaluation (ringCatSheaf R) W).map
      ((biproductIsoFree (R := R) I).inv ≫ (biproduct.isoProduct _).hom) ≫
    (PreservesProduct.iso (evaluation (ringCatSheaf R) W) _).hom ≫
    (ModuleCat.piIsoPi fun _ : I ↦ (evaluation (ringCatSheaf R) W).obj (𝟙_ _)).hom) ≫
      ModuleCat.ofHom (LinearMap.proj i) = _
  rw [Category.assoc, Category.assoc, ModuleCat.piIsoPi_hom_ker_subtype, PreservesProduct.iso_hom,
    piComparison_comp_π, ← Functor.map_comp, biproduct.isoProduct_hom, Category.assoc,
    limit.lift_π, Fan.mk_π_app]

/-- If there is an epimorphism `free J ⟶ free K` between free sheaves of modules on finite types
with `|J| < |K|`, then the sheaf of rings vanishes: all its rings of sections are trivial. -/
theorem subsingleton_of_epi_free_of_card_lt {I K : Type u} [Finite I] [Finite K]
    (f : free (R := ringCatSheaf R) I ⟶ free K) [Epi f] (h : Nat.card I < Nat.card K)
    (W : Cᵒᵖ) : Subsingleton ((ringCatSheaf R).obj.obj W) := by
  by_contra hW
  rw [not_subsingleton_iff_nontrivial] at hW
  -- `ringCatSheaf` forgets commutativity, so the commutative ring structure on the sections of
  -- `R` over `W` is recovered from `R` itself; the strong rank condition needs it.
  let : CommRing ((ringCatSheaf R).obj.obj W) := inferInstanceAs (CommRing (R.obj.obj W))
  have := Fintype.ofFinite I
  have := Fintype.ofFinite K
  let g : free (R := ringCatSheaf R) K ⟶ free I :=
    (dualFreeIso (R := R) K).inv ≫ (MonoidalClosed.pre f).app (𝟙_ _) ≫ (dualFreeIso (R := R) I).hom
  have hg : Mono g := inferInstance
  have hg' : Mono ((evaluation (ringCatSheaf R) W).map g) := inferInstance
  let φ := (evaluationFreeIso (R := R) K W).inv ≫ (evaluation (ringCatSheaf R) W).map g ≫
    (evaluationFreeIso (R := R) I W).hom
  have hφ : Function.Injective φ.hom := (ModuleCat.mono_iff_injective φ).1 inferInstance
  have hle := LinearMap.finrank_le_finrank_of_injective hφ
  rw [Module.finrank_fintype_fun_eq_card, Module.finrank_fintype_fun_eq_card] at hle
  rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card] at h
  omega

/-- If there is an epimorphism from a free sheaf of modules on a finite type to the free sheaf of
modules on an infinite type, then the sheaf of rings vanishes. -/
theorem subsingleton_of_epi_free_of_infinite {I K : Type u} [Finite I] [Infinite K]
    (f : free (R := ringCatSheaf R) I ⟶ free K) [Epi f] (W : Cᵒᵖ) :
    Subsingleton ((ringCatSheaf R).obj.obj W) := by
  classical
  obtain ⟨s, hs⟩ := Infinite.exists_subset_card_eq K (Nat.card I + 1)
  -- The projection of `free K` onto the summands indexed by `s`, a retraction of `freeMap`.
  let r : free (R := ringCatSheaf R) K ⟶ free (R := ringCatSheaf R) s :=
    (freeHomEquiv _).symm fun k ↦
      if hk : k ∈ s then freeSection ⟨k, hk⟩ else (free s).unitHomEquiv 0
  have hr : freeMap (R := ringCatSheaf R) (Subtype.val : s → K) ≫ r = 𝟙 _ := by
    apply (freeHomEquiv _).injective
    funext j
    rw [freeHomEquiv_comp_apply, freeHomEquiv_freeMap, Function.comp_apply,
      sectionsMap_freeHomEquiv_symm_freeSection, dite_eq_left j.2, Subtype.coe_eta]
  have : IsSplitEpi r := ⟨⟨⟨freeMap Subtype.val, hr⟩⟩⟩
  refine subsingleton_of_epi_free_of_card_lt (f ≫ r) ?_ W
  rw [Nat.card_eq_finsetCard, hs]
  exact Nat.lt_succ_self _

end Free

section GeneratingSections

variable {N : SheafOfModules.{u} (ringCatSheaf R)}

/-- A sheaf of modules which is free, on a possibly infinite index type, and generated by finitely
many sections is free on a finite type. If the given basis is infinite, the sheaf of rings
vanishes and the sheaf is free on the empty type. -/
theorem _root_.SheafOfModules.GeneratingSections.exists_isIso_π_isFiniteType
    (σ τ : N.GeneratingSections) [hσ : IsIso σ.π] [hτ : τ.IsFiniteType] :
    ∃ ρ : N.GeneratingSections, IsIso ρ.π ∧ ρ.IsFiniteType := by
  by_cases hI : Finite σ.I
  · exact ⟨σ, inferInstance, ⟨hI⟩⟩
  rw [not_finite_iff_infinite] at hI
  have hN : IsZero N :=
    isZero_of_forall_subsingleton (subsingleton_of_epi_free_of_infinite (τ.π ≫ inv σ.π)) N
  have hfree : IsZero (free (R := ringCatSheaf R) PEmpty.{u + 1}) := isZero_free PEmpty
  let ρ : N.GeneratingSections := ⟨PEmpty, fun x ↦ x.elim, ⟨fun g h _ ↦ hN.eq_of_src g h⟩⟩
  refine ⟨ρ, ?_, ⟨inferInstanceAs (Finite PEmpty)⟩⟩
  rw [hfree.eq_of_src ρ.π (hfree.iso hN).hom]
  infer_instance

end GeneratingSections

section LocallyFree

omit [HasWeakSheafify J AddCommGrpCat.{u}] [J.WEqualsLocallyBijective AddCommGrpCat.{u}]

variable [HasPullbacks C]
  [∀ X, (J.over X).HasSheafCompose (forget₂ CommRingCat RingCat.{u})]
  [∀ X, HasSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ X, (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]
  (M : SheafOfModules.{u} (ringCatSheaf R))

/-- A locally free and finitely presented sheaf of modules admits locally free data with finite
local bases. -/
theorem _root_.SheafOfModules.IsLocallyFree.exists_isLocallyFreeData_isFiniteType
    [M.IsLocallyFree] [M.IsFinitePresentation] :
    ∃ q : M.LocalGeneratorsData.{u}, q.IsLocallyFreeData ∧ q.IsFiniteType := by
  obtain ⟨q, hq⟩ := IsLocallyFree.exists_isLocallyFreeData (M := M)
  obtain ⟨p, hp⟩ := IsFinitePresentation.exists_quasicoherentData M
  let r := GrothendieckTopology.CoversTop.commonRefinement q.coversTop p.coversTop
  have h : ∀ i : r.I, ∃ ρ : (M.over (r.X i)).GeneratingSections,
      IsIso ρ.π ∧ ρ.IsFiniteType := fun i ↦
    have h₁ : (q.ofRefinement r.X r.coversTop r.leftIndex r.left).IsLocallyFreeData :=
      inferInstance
    have h₂ : (p.ofRefinement r.X r.coversTop r.rightIndex r.right).IsFinitePresentation :=
      inferInstance
    -- The slice's sheaf of rings is `ringCatSheaf (R.over _)` only up to unfolding, so the
    -- instances are passed explicitly.
    GeneratingSections.exists_isIso_π_isFiniteType (R := R.over (r.X i))
      ((q.ofRefinement r.X r.coversTop r.leftIndex r.left).generators i)
      ((p.ofRefinement r.X r.coversTop r.rightIndex r.right).presentation i).generators
      (hσ := h₁.isIso i) (hτ := (h₂.isFinite_presentation i).isFiniteType_generators)
  choose ρ hρ using h
  exact ⟨{ I := r.I, X := r.X, coversTop := r.coversTop, generators := ρ },
    ⟨fun i ↦ (hρ i).1⟩, ⟨fun i ↦ (hρ i).2⟩⟩

/-- A sheaf of modules is finite locally free, that is, locally free and finitely presented, if
and only if it admits locally free data with finite local bases. -/
theorem _root_.SheafOfModules.isFiniteLocallyFree_iff_exists_isLocallyFreeData_isFiniteType :
    isFiniteLocallyFree (ringCatSheaf R) M ↔
      ∃ q : M.LocalGeneratorsData.{u}, q.IsLocallyFreeData ∧ q.IsFiniteType :=
  ⟨fun ⟨_, _⟩ ↦ IsLocallyFree.exists_isLocallyFreeData_isFiniteType M,
    fun ⟨q, hq, hq'⟩ ↦ ⟨q.isLocallyFree, hq.isFinitePresentation hq'⟩⟩

end LocallyFree

end SheafOfModules

end

end TauCeti
