/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.CartanDieudonne
-- Private: the graded centre, the scalar units of the Lipschitz group, and unit lifting are used
-- only inside the proof.
import TauCeti.LinearAlgebra.CliffordAlgebra.Basic
import TauCeti.LinearAlgebra.CliffordAlgebra.Lipschitz.Generators
import TauCeti.Algebra.GroupWithZero.Units.Basic

/-!
# The Lipschitz group as the twisted-conjugation stabiliser of the vectors

Mathlib defines `lipschitzGroup Q` as the subgroup of Clifford units generated by the invertible
vectors and proves that twisted conjugation `v ↦ involute x * ι Q v * x⁻¹` by such a unit carries
vectors to vectors (`lipschitzGroup.involute_act_ι_mem_range_ι`), recording as an open question
whether, in finite dimensions, every unit whose twisted conjugation preserves the vectors — an
element of the classical Clifford group — is generated by invertible vectors. This file settles
that question for a nondegenerate form on a finite-dimensional space over a field of
characteristic not two, where the two groups coincide.

Twisted conjugation by such a unit `x` induces a linear endomorphism of the quadratic space; it
preserves the form because the twisted conjugate of `ι v` squares to `Q v`, and it is injective
because `x` is a unit, hence an isometry. By Cartan–Dieudonné some Lipschitz element `y` induces
the same isometry (`CliffordAlgebra.lipschitzToOrthogonal_surjective`), so `y⁻¹ * x`
graded-commutes with every vector and is a scalar
(`CliffordAlgebra.exists_eq_algebraMap_of_involute_mul_ι_eq_ι_mul`). Scalar units lie in the
Lipschitz group as soon as some vector is anisotropic, and that hypothesis cannot be dropped: on
the zero space the Lipschitz group is trivial, while every scalar unit preserves the zero space of
vectors.

## Main results

* `CliffordAlgebra.mem_lipschitzGroup_of_involute_act_ι_mem_range_ι`: a unit whose twisted
  conjugation preserves the vectors lies in the Lipschitz group.
* `CliffordAlgebra.mem_lipschitzGroup_iff_involute_act_ι_mem_range_ι`: the Lipschitz group is
  exactly the classical Clifford group.

## References

* C. Chevalley, *The Algebraic Theory of Spinors* (1954), Chapter II.
* H. B. Lawson and M.-L. Michelsohn, *Spin Geometry* (1989), Chapter I, §2.
-/

public section

namespace CliffordAlgebra

open TauCeti

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  [FiniteDimensional K V] [Invertible (2 : K)] (Q : QuadraticForm K V)

/-- Twisted conjugation by a unit preserving the vectors induces an isometry of the quadratic
space. This is an intermediate step: once the unit is known to be Lipschitz, the isometry is
`lipschitzToOrthogonal`. -/
private theorem exists_mem_orthogonalGroup_of_involute_act_ι_mem_range_ι
    {x : (CliffordAlgebra Q)ˣ}
    (hx : ∀ m, involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ ∈ LinearMap.range (ι Q)) :
    ∃ g ∈ QuadraticMap.orthogonalGroup Q,
      ∀ m, ι Q (g m) = involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ := by
  -- The endomorphism of the quadratic space induced by twisted conjugation.
  let g₀ : V →ₗ[K] V :=
    (ιInv Q).comp (((LinearMap.mulRight K ((x⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q)).comp
      (LinearMap.mulLeft K (involute (Q := Q) (x : CliffordAlgebra Q)))).comp (ι Q))
  have hg₀ (m : V) : ι Q (g₀ m) = involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ := ι_ιInv_of_mem Q (hx m)
  -- Applying the grade involution gives the other spelling of the twisted conjugate.
  have hg₀' (m : V) :
      ι Q (g₀ m) =
        ↑x * ι Q m * involute (Q := Q) ((x⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) := by
    have h := congrArg (involute (Q := Q)) (hg₀ m)
    rw [involute_ι, map_mul, map_mul, involute_involute, involute_ι, mul_neg, neg_mul] at h
    exact neg_injective h
  -- The two spellings multiply to the scalar `Q m`, so the endomorphism preserves the form.
  have hQg (m : V) : Q (g₀ m) = Q m := by
    apply algebraMap_injective Q
    rw [← ι_sq_scalar, ← ι_sq_scalar]
    calc ι Q (g₀ m) * ι Q (g₀ m)
        = (involute (Q := Q) ↑x * ι Q m * ↑x⁻¹) *
            (↑x * ι Q m *
              involute (Q := Q) ((x⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q)) := by
          rw [← hg₀ m, ← hg₀' m]
      _ = involute (Q := Q) ↑x * (ι Q m * (↑x⁻¹ * ↑x) * ι Q m) *
            involute (Q := Q) ((x⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) := by
          simp only [mul_assoc]
      _ = ι Q m * ι Q m := by
          rw [Units.inv_mul, mul_one, ι_sq_scalar, ← Algebra.commutes, mul_assoc, ← map_mul,
            Units.mul_inv, map_one, mul_one]
  -- It is injective, since `x` is a unit, hence an automorphism in finite dimension.
  have hinj : Function.Injective g₀ := by
    intro m₁ m₂ h
    have h' := congrArg (ι Q) h
    rw [hg₀, hg₀] at h'
    exact ι_injective Q ((x.isUnit.map (involute (Q := Q))).mul_left_cancel
      ((Units.mul_left_inj x⁻¹).mp h'))
  refine ⟨LinearEquiv.ofInjectiveEndo g₀ hinj, QuadraticMap.mem_orthogonalGroup_iff.mpr fun m => ?_,
    fun m => ?_⟩ <;>
    rw [LinearEquiv.coe_ofInjectiveEndo]
  · exact hQg m
  · exact hg₀ m

/-- **A unit whose twisted conjugation preserves the vectors is a Lipschitz element.** For a
nondegenerate form on a finite-dimensional space representing a unit, Mathlib's closure-defined
Lipschitz group contains the classical Clifford group. -/
theorem mem_lipschitzGroup_of_involute_act_ι_mem_range_ι (hQ : Q.Nondegenerate)
    (hv : ∃ v, IsUnit (Q v)) {x : (CliffordAlgebra Q)ˣ}
    (hx : ∀ m, involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ ∈ LinearMap.range (ι Q)) :
    x ∈ lipschitzGroup Q := by
  obtain ⟨g, hgO, hg⟩ := exists_mem_orthogonalGroup_of_involute_act_ι_mem_range_ι Q hx
  -- By Cartan–Dieudonné, some Lipschitz element `y` induces the same isometry. The surjectivity
  -- theorem is stated for the instance `invertibleOfNonzero`; `Invertible` is a subsingleton.
  have hsurj : Function.Surjective (lipschitzToOrthogonal Q) := by
    have : NeZero (2 : K) := ⟨Invertible.ne_zero 2⟩
    convert lipschitzToOrthogonal_surjective Q hQ using 3
    exact Subsingleton.elim _ _
  obtain ⟨y, hy⟩ := hsurj ⟨g, hgO⟩
  have hyx (m : V) :
      involute (Q := Q) ((y : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) * ι Q m *
          (((y : (CliffordAlgebra Q)ˣ)⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) =
        involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ := by
    rw [← ι_lipschitzVectorAction_apply, ← coe_lipschitzToOrthogonal_apply, hy, ← hg m]
  -- Hence `y⁻¹ * x` graded-commutes with every vector, so it is a scalar unit.
  have hz (m : V) :
      involute (Q := Q) (((y : (CliffordAlgebra Q)ˣ)⁻¹ * x : (CliffordAlgebra Q)ˣ) :
          CliffordAlgebra Q) * ι Q m =
        ι Q m *
          (((y : (CliffordAlgebra Q)ˣ)⁻¹ * x : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) := by
    have hinv : involute (Q := Q)
        ((((y : (CliffordAlgebra Q)ˣ)⁻¹ : (CliffordAlgebra Q)ˣ)) : CliffordAlgebra Q) *
          involute (Q := Q) ((y : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) = 1 := by
      rw [← map_mul, Units.inv_mul, map_one]
    calc involute (Q := Q) (((y : (CliffordAlgebra Q)ˣ)⁻¹ * x : (CliffordAlgebra Q)ˣ) :
            CliffordAlgebra Q) * ι Q m
        = involute (Q := Q)
              ((((y : (CliffordAlgebra Q)ˣ)⁻¹ : (CliffordAlgebra Q)ˣ)) : CliffordAlgebra Q) *
            (involute (Q := Q) ↑x * ι Q m * ↑x⁻¹) * ↑x := by
          simp only [Units.val_mul, map_mul, mul_assoc, Units.inv_mul, mul_one]
      _ = involute (Q := Q)
              ((((y : (CliffordAlgebra Q)ˣ)⁻¹ : (CliffordAlgebra Q)ˣ)) : CliffordAlgebra Q) *
            (involute (Q := Q) ((y : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q) * ι Q m *
              (((y : (CliffordAlgebra Q)ˣ)⁻¹ : (CliffordAlgebra Q)ˣ) : CliffordAlgebra Q)) *
            ↑x := by
          rw [hyx m]
      _ = ι Q m * (((y : (CliffordAlgebra Q)ˣ)⁻¹ * x : (CliffordAlgebra Q)ˣ) :
            CliffordAlgebra Q) := by
          simp only [Units.val_mul, ← mul_assoc, hinv, one_mul]
  obtain ⟨r, hr⟩ := exists_eq_algebraMap_of_involute_mul_ι_eq_ι_mul Q hQ _ hz
  have : Nontrivial (CliffordAlgebra Q) := (algebraMap_injective Q).nontrivial
  obtain ⟨a, ha⟩ := (TauCeti.mem_range_iff_exists_units_map_eq (algebraMap K (CliffordAlgebra Q))
    ((y : (CliffordAlgebra Q)ˣ)⁻¹ * x)).mp ⟨r, hr.symm⟩
  have hzmem : (y : (CliffordAlgebra Q)ˣ)⁻¹ * x ∈ lipschitzGroup Q :=
    ha ▸ unitsMap_algebraMap_mem_lipschitzGroup hv a
  simpa using mul_mem y.2 hzmem

/-- **Mathlib's Lipschitz group is the classical Clifford group.** For a nondegenerate form on a
finite-dimensional space representing a unit, a Clifford unit is generated by invertible vectors
exactly when its twisted conjugation preserves the vectors. -/
theorem mem_lipschitzGroup_iff_involute_act_ι_mem_range_ι (hQ : Q.Nondegenerate)
    (hv : ∃ v, IsUnit (Q v)) {x : (CliffordAlgebra Q)ˣ} :
    x ∈ lipschitzGroup Q ↔
      ∀ m, involute (Q := Q) ↑x * ι Q m * ↑x⁻¹ ∈ LinearMap.range (ι Q) :=
  ⟨fun hx m => lipschitzGroup.involute_act_ι_mem_range_ι hx m,
    mem_lipschitzGroup_of_involute_act_ι_mem_range_ι Q hQ hv⟩

end CliffordAlgebra
