/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import TauCeti.Topology.Algebra.ContinuousMonoidHom
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicUnits
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Procyclic

/-!
# The kernel of a character with two marked generators

Let `G` be a pro-`p` group topologically generated by two *marked* elements `a`, `b` together with
a set `S`, and let `χ : G → B` be a continuous homomorphism into a pro-`p` group that kills `S`.
The kernel of `χ` contains the closed normal closure of `S`, but is larger: the marked values
`χ a`, `χ b` satisfy relations, and the corresponding words in `a`, `b` lie in the kernel too. Let
`N` be a closed normal subgroup inside `ker χ` containing `S` and the commutator `(a, b)`. Modulo
`N` the marked generators commute and topologically generate, so every class is a product
`a ^ s b ^ t` of `p`-adic powers (`TauCeti.IsProP.exists_padicPow_mul_padicPow_eq_of_commute`),
and the kernel of `χ` is exactly `N` as soon as every relation `(χ a) ^ s (χ b) ^ t = 1` between
the marked values forces the word `a ^ s b ^ t` into `N`
(`TauCeti.IsProP.ker_eq_of_forall_padicPow_mul_padicPow_mem`).

The case of interest is a character `χ : G → ℤ_2ˣ` whose marked values are `χ a = v` with
`-v ∈ 1 + 4ℤ_2` and `χ b = u ∈ 1 + 4ℤ_2`, `u ≠ 1`, so that the image `⟨v, u⟩` is not procyclic:
it contains `-1` together with a nontrivial element of `1 + 4ℤ_2`. Here `v ^ 2 = u ^ m` for a
`2`-adic exponent `m`, and the kernel of `χ` is the closed normal closure of `S`, `a ^ 2 b ^ (-m)`
and `(a, b)` (`TauCeti.IsProP.ker_eq_topologicalClosure_normalClosure_of_neg_mem_unitsPrincipal`):
a relation `v ^ s u ^ t = 1` first forces `s` to be even, by the sign of `v`
(`TauCeti.two_dvd_of_padicPow_mul_padicPow_eq_one`), and then `t = -m s / 2`, because `u` has
infinite order. This is the kernel `X = ker χ` of the orientation of a Demushkin group of even
rank with `q = 2` whose image is `{±1} × U^(f)`, on which Labute's module `E = X ⧸ (X, X)` is
built; the description of `X` by normal generators is what makes `E` a finitely generated module
over `ℤ_2[[G ⧸ X]]` with named generators.

## Main results

* `TauCeti.IsProP.ker_eq_of_forall_padicPow_mul_padicPow_mem`: the kernel of a character with
  two marked generators is a closed normal subgroup `N` containing the unmarked generators and
  the commutator of the marked ones, once every relation between the marked values lifts to `N`.
* `TauCeti.IsProP.ker_eq_topologicalClosure_normalClosure_of_neg_mem_unitsPrincipal`: for a
  character to `ℤ_2ˣ` with marked values `v`, `u` generating a non-procyclic subgroup, the kernel
  is the closed normal closure of the unmarked generators, `a ^ 2 b ^ (-m)` and `(a, b)`, where
  `u ^ m = v ^ 2`.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), §4.
-/

public section

open scoped commutatorElement

namespace TauCeti

namespace IsProP

variable {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]

/-! ### The kernel of a character with two marked generators -/

section Kernel

variable {B : Type*} [Group B] [TopologicalSpace B] [IsTopologicalGroup B] [CompactSpace B]
  [TotallyDisconnectedSpace B] (hG : IsProP p G) (hB : IsProP p B) (χ : G →ₜ* B)
include hG hB

/-- **The kernel of a character with two marked generators.** Let `G` be a pro-`p` group
topologically generated by `a`, `b` and a set `S`, let `χ : G → B` be a continuous homomorphism
into a pro-`p` group, and let `N` be a closed normal subgroup of `G` inside `ker χ` containing `S`
and the commutator `(a, b)`. If every relation `(χ a) ^ s (χ b) ^ t = 1` between the marked values,
with `p`-adic exponents, forces `a ^ s b ^ t ∈ N`, then `ker χ = N`. -/
theorem ker_eq_of_forall_padicPow_mul_padicPow_mem {a b : G} {S : Set G}
    (hgen : (Subgroup.closure (insert a (insert b S))).topologicalClosure = ⊤)
    {N : Subgroup G} [N.Normal] [IsClosed (N : Set G)] (hN : N ≤ χ.toMonoidHom.ker)
    (hS : S ⊆ N) (hab : ⁅a, b⁆ ∈ N)
    (h : ∀ s t : ℤ_[p], hB.padicPow (χ a) s * hB.padicPow (χ b) t = 1 →
      hG.padicPow a s * hG.padicPow b t ∈ N) :
    χ.toMonoidHom.ker = N := by
  refine le_antisymm (fun x hx ↦ ?_) hN
  have hQ : IsProP p (G ⧸ N) := hG.quotient N
  -- The marked generators commute modulo `N` and topologically generate the quotient.
  have hcomm : Commute (a : G ⧸ N) (b : G ⧸ N) := by
    have h1 : QuotientGroup.mk' N ⁅a, b⁆ = 1 := (QuotientGroup.eq_one_iff _).2 hab
    rw [map_commutatorElement, commutatorElement_eq_one_iff_commute] at h1
    exact h1
  have hgenQ : (Subgroup.closure ({(a : G ⧸ N), (b : G ⧸ N)} : Set (G ⧸ N))).topologicalClosure =
      ⊤ := by
    have hpre : (Subgroup.closure (insert a (insert b S))).topologicalClosure ≤
        (Subgroup.closure ({(a : G ⧸ N), (b : G ⧸ N)} : Set (G ⧸ N))).topologicalClosure.comap
          (QuotientGroup.mk' N) := by
      refine Subgroup.topologicalClosure_minimal _ ((Subgroup.closure_le _).2 ?_)
        ((Subgroup.isClosed_topologicalClosure _).preimage QuotientGroup.continuous_mk)
      rintro x (rfl | rfl | hx)
      · exact Subgroup.le_topologicalClosure _ (Subgroup.subset_closure (by simp))
      · exact Subgroup.le_topologicalClosure _ (Subgroup.subset_closure (by simp))
      · rw [SetLike.mem_coe, Subgroup.mem_comap, QuotientGroup.mk'_apply,
          (QuotientGroup.eq_one_iff x).2 (hS hx)]
        exact one_mem _
    refine top_le_iff.1 fun q _ ↦ ?_
    obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective q
    exact hpre (hgen ▸ Subgroup.mem_top g)
  -- Write the class of `x` as `a ^ s b ^ t` modulo `N`.
  obtain ⟨s, t, hst⟩ := hQ.exists_padicPow_mul_padicPow_eq_of_commute hcomm hgenQ (x : G ⧸ N)
  have ea : ((hG.padicPow a s : G) : G ⧸ N) = hQ.padicPow (a : G ⧸ N) s :=
    hG.map_padicPow hQ (QuotientGroup.mk' N) QuotientGroup.continuous_mk a s
  have eb : ((hG.padicPow b t : G) : G ⧸ N) = hQ.padicPow (b : G ⧸ N) t :=
    hG.map_padicPow hQ (QuotientGroup.mk' N) QuotientGroup.continuous_mk b t
  rw [← ea, ← eb, ← QuotientGroup.mk_mul, QuotientGroup.eq] at hst
  -- The word `a ^ s b ^ t` lies in the kernel, so the relation holds between the marked values.
  have hχ : hB.padicPow (χ a) s * hB.padicPow (χ b) t = 1 := by
    have ha : χ (hG.padicPow a s) = hB.padicPow (χ a) s :=
      hG.map_padicPow hB χ.toMonoidHom χ.continuous a s
    have hb : χ (hG.padicPow b t) = hB.padicPow (χ b) t :=
      hG.map_padicPow hB χ.toMonoidHom χ.continuous b t
    have hmem := hN hst
    rw [MonoidHom.mem_ker, map_mul, MonoidHom.mem_ker.mp hx, mul_one, map_inv, inv_eq_one,
      map_mul] at hmem
    rw [← ha, ← hb]
    exact hmem
  have hx' : x = (hG.padicPow a s * hG.padicPow b t) *
      ((hG.padicPow a s * hG.padicPow b t)⁻¹ * x) := by group
  rw [hx']
  exact N.mul_mem (h s t hχ) hst

end Kernel

end IsProP

/-! ### Characters to `ℤ_2ˣ` with a non-procyclic image -/

section DyadicUnits

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [TotallyDisconnectedSpace G]

/-- **The kernel of a character to `ℤ_2ˣ` with two marked generators of non-procyclic image.**
Let `G` be a pro-`2` group topologically generated by `a`, `b` and a set `S`, and let
`χ : G → ℤ_2ˣ` be a continuous character trivial on `S` with `-χ a ∈ 1 + 4ℤ_2` and
`χ b ∈ 1 + 4ℤ_2`, `χ b ≠ 1`, so that its image is generated by an element of order two and an
element of infinite order. If `(χ b) ^ m = (χ a) ^ 2`, then `ker χ` is the closed normal closure
of `S`, `a ^ 2 b ^ (-m)` and `(a, b)`. -/
theorem IsProP.ker_eq_topologicalClosure_normalClosure_of_neg_mem_unitsPrincipal
    (hG : IsProP 2 G) (χ : G →ₜ* ℤ_[2]ˣ) {a b : G} {S : Set G}
    (hgen : (Subgroup.closure (insert a (insert b S))).topologicalClosure = ⊤)
    (hS : ∀ x ∈ S, χ x = 1) (hv : -χ a ∈ unitsPrincipal 2 2) (hu : χ b ∈ unitsPrincipal 2 2)
    (hu1 : χ b ≠ 1) {m : ℤ_[2]} (hm : isProP_units_padicInt_two.padicPow (χ b) m = χ a ^ 2) :
    χ.toMonoidHom.ker = (Subgroup.normalClosure
      (insert (a ^ 2 * (hG.padicPow b m)⁻¹) (insert ⁅a, b⁆ S))).topologicalClosure := by
  set N := (Subgroup.normalClosure
    (insert (a ^ 2 * (hG.padicPow b m)⁻¹) (insert ⁅a, b⁆ S))).topologicalClosure with hNdef
  have hRN : ∀ x ∈ insert (a ^ 2 * (hG.padicPow b m)⁻¹) (insert ⁅a, b⁆ S), x ∈ N :=
    fun x hx ↦ Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure hx)
  have hab : ⁅a, b⁆ ∈ N := hRN _ (Set.mem_insert_of_mem _ (Set.mem_insert _ _))
  have hrel : a ^ 2 * (hG.padicPow b m)⁻¹ ∈ N := hRN _ (Set.mem_insert _ _)
  have hQ : IsProP 2 (G ⧸ N) := hG.quotient N
  have hcomm : Commute (a : G ⧸ N) (b : G ⧸ N) := by
    have h1 : QuotientGroup.mk' N ⁅a, b⁆ = 1 := (QuotientGroup.eq_one_iff _).2 hab
    rw [map_commutatorElement, commutatorElement_eq_one_iff_commute] at h1
    exact h1
  refine hG.ker_eq_of_forall_padicPow_mul_padicPow_mem isProP_units_padicInt_two χ hgen ?_
    (fun x hx ↦ hRN x (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ hx))) hab
    fun s t hst ↦ ?_
  · -- The normal generators lie in the kernel.
    refine (Subgroup.topologicalClosure_normalClosure_le_iff χ.isClosed_ker).2 ?_
    rintro x (rfl | rfl | hx)
    · have hb : χ (hG.padicPow b m) = isProP_units_padicInt_two.padicPow (χ b) m :=
        hG.map_padicPow isProP_units_padicInt_two χ.toMonoidHom χ.continuous b m
      rw [SetLike.mem_coe, MonoidHom.mem_ker, ContinuousMonoidHom.coe_toMonoidHom,
        MonoidHom.coe_ofClass, map_mul, map_pow, map_inv, hb, hm, mul_inv_cancel]
    · rw [SetLike.mem_coe, MonoidHom.mem_ker, ContinuousMonoidHom.coe_toMonoidHom,
        MonoidHom.coe_ofClass, map_commutatorElement, commutatorElement_eq_one_iff_commute]
      exact Commute.all _ _
    · exact MonoidHom.mem_ker.2 (hS x hx)
  -- A relation `v ^ s u ^ t = 1` forces `s = 2 s'` and `t = -m s'`.
  obtain ⟨s', rfl⟩ := two_dvd_of_padicPow_mul_padicPow_eq_one hv hu hst
  have h1 : isProP_units_padicInt_two.padicPow (χ a) (2 * s') =
      isProP_units_padicInt_two.padicPow (χ b) (m * s') := by
    rw [IsProP.padicPow_mul, IsProP.padicPow_ofNat, ← hm, ← IsProP.padicPow_mul]
  rw [h1, ← IsProP.padicPow_add] at hst
  have ht : m * s' + t = 0 := by
    have hinj := isProP_units_padicInt_two.padicPowHom_injective_of_not_isOfFinOrder
      (not_isOfFinOrder_of_mem_unitsPrincipal two_pos (fun _ ↦ le_rfl) hu hu1)
    have := @hinj (Multiplicative.ofAdd (m * s' + t)) (Multiplicative.ofAdd 0)
      (by rw [IsProP.padicPowHom_apply, IsProP.padicPowHom_apply, toAdd_ofAdd, toAdd_ofAdd, hst,
        IsProP.padicPow_zero])
    exact Multiplicative.ofAdd.injective this
  rw [eq_neg_of_add_eq_zero_right ht]
  -- The word `a ^ (2 s') b ^ (-m s')` is `(a ^ 2 b ^ (-m)) ^ s'` modulo `N`.
  have ea : ((hG.padicPow a (2 * s') : G) : G ⧸ N) = hQ.padicPow (a : G ⧸ N) (2 * s') :=
    hG.map_padicPow hQ (QuotientGroup.mk' N) QuotientGroup.continuous_mk a _
  have eb : ((hG.padicPow b (-(m * s')) : G) : G ⧸ N) = hQ.padicPow (b : G ⧸ N) (-(m * s')) :=
    hG.map_padicPow hQ (QuotientGroup.mk' N) QuotientGroup.continuous_mk b _
  have em : ((hG.padicPow b m : G) : G ⧸ N) = hQ.padicPow (b : G ⧸ N) m :=
    hG.map_padicPow hQ (QuotientGroup.mk' N) QuotientGroup.continuous_mk b m
  have hrel' : (a : G ⧸ N) ^ 2 * (hQ.padicPow (b : G ⧸ N) m)⁻¹ = 1 := by
    rw [← em, ← QuotientGroup.mk_pow, ← QuotientGroup.mk_inv, ← QuotientGroup.mk_mul,
      QuotientGroup.eq_one_iff]
    exact hrel
  have hc : Commute ((a : G ⧸ N) ^ 2) (hQ.padicPow (b : G ⧸ N) m)⁻¹ :=
    (hQ.commute_padicPow_right (hcomm.pow_left 2) m).inv_right
  rw [← QuotientGroup.eq_one_iff (N := N), QuotientGroup.mk_mul, ea, eb]
  calc hQ.padicPow (a : G ⧸ N) (2 * s') * hQ.padicPow (b : G ⧸ N) (-(m * s'))
      = hQ.padicPow ((a : G ⧸ N) ^ 2 * (hQ.padicPow (b : G ⧸ N) m)⁻¹) s' := by
        rw [hQ.mul_padicPow _ _ hc s', hQ.padicPow_mul, hQ.padicPow_ofNat, hQ.padicPow_neg,
          hQ.padicPow_mul, hQ.inv_padicPow]
    _ = 1 := by rw [hrel', hQ.one_padicPow]

end DyadicUnits

end TauCeti
