/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.CompletedGroupAlgebraModule
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Subgroup
public import TauCeti.Topology.Algebra.Group.TopologicalAbelianization

/-!
# The abelianized kernel of a character as a module over the completed group algebra

Let `G` be a pro-`p` group and `N` a closed normal subgroup. The topological abelianization
`N^{ab} = N ⧸ (N, N)` is an abelian pro-`p` group on which `G ⧸ N` acts continuously by
conjugation, so it is a compact module over the completed group algebra `ℤ_p[[G ⧸ N]]`
(`TauCeti.IsProP.completedGroupAlgebraModule`). This file proves that this module is **finitely
generated** as soon as `N` is the closed normal closure of a finite set `S`: the conjugates of `S`
generate a dense subgroup of `N`, so the `(G ⧸ N)`-orbit of the classes of the elements of `S`
generates a dense subgroup of `N^{ab}`, and a finite set with a dense orbit spans a compact module
over a compact ring.

The kernel of a continuous character `χ : G → A` to a commutative group, for `G` topologically
finitely generated, is such a subgroup. It contains the closure of the commutator subgroup, which
is normally generated by the commutators of a finite generating set, and its image in the
abelianization `G^{ab}` is a closed subgroup of a topologically finitely generated abelian pro-`p`
group, hence topologically generated by finitely many elements, which lift to the kernel.

For `F` free pro-`p` of finite rank and `χ : F → ℤ_pˣ` an orientation character, the module
obtained is `E = X ⧸ (X, X)`, `X = ker χ`, over `Λ = ℤ_p[[Γ]]`, `Γ = F ⧸ X ≅ Im χ`, on which
Labute's classification of Demushkin groups runs (Labute, §4, p. 121): `E` is generated over `Λ`
by finitely many classes of elements of `X`, and it is this finite generation that lets the
relator class be expressed as a `Λ`-combination of generators.

**The convention for the action.** Labute writes the action of `Γ` on `E` as
`ȳ · x̄ = [y⁻¹ x y]` (§4 Definition, p. 121). The module structure used here is Mathlib's
conjugation action `ȳ • x̄ = [y x y⁻¹]` (`TopologicalAbelianization.mk_smul_mk`, extended to the
group elements of `Λ` by `TauCeti.IsProP.completedGroupAlgebraModule_of_smul`), so Labute's
action is `ȳ⁻¹ • x̄` (`TopologicalAbelianization.mk_inv_smul_mk`): the two differ by the inversion
of `Γ`. Since `Γ ≅ Im χ` is commutative, inversion is a continuous automorphism of `Γ`, and
`TauCeti.completedGroupAlgebra.map` turns it into an involutive algebra automorphism `ι` of `Λ`
with Labute's scalar action `l ·_L ξ = ι l • ξ`. The two module structures therefore have the
same submodules, the same spans and the same generating sets, and the finite generation proved
here holds verbatim for Labute's action; only the coefficients of a `Λ`-combination of given
generators change, by `ι`. No such coefficients are computed in this file.

## Main results

* `TauCeti.IsProP.module_finite_topologicalAbelianization`: if `N` is the closed normal closure
  of a finite set in a pro-`p` group `G`, then `N^{ab}` is a finitely generated
  `ℤ_p[[G ⧸ N]]`-module.
* `TauCeti.IsProP.exists_finite_topologicalClosure_normalClosure_eq_ker`: the kernel of a
  continuous homomorphism from a topologically finitely generated pro-`p` group to a commutative
  `T1` group is the closed normal closure of a finite set.
* `TauCeti.IsProP.module_finite_topologicalAbelianization_ker`: Labute's module, the
  abelianized kernel of a continuous character of a topologically finitely generated pro-`p`
  group, is a finitely generated module over the completed group algebra of the image.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), §4.
-/

public section

open scoped Pointwise commutatorElement

namespace TauCeti.IsProP

variable {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G]

section NormalClosure

variable (hG : IsProP p G) (N : Subgroup G) [N.Normal]
include hG

omit [Fact p.Prime] [N.Normal] in
/-- The topological abelianization of a subgroup of a pro-`p` group is pro-`p`. -/
theorem topologicalAbelianization : IsProP p (TopologicalAbelianization N) :=
  (hG.subgroup N).quotient _

/-- **The abelianization of a finitely normally generated closed subgroup is a finitely generated
module over the completed group algebra.** If `N` is the closed normal closure of a finite set `S`
in a pro-`p` group `G`, then `N^{ab}` is a finitely generated `ℤ_p[[G ⧸ N]]`-module, for the
module structure `TauCeti.IsProP.completedGroupAlgebraModule` through conjugation: it is spanned by
the classes of the elements of `S`, whose `(G ⧸ N)`-orbit generates a dense subgroup. -/
theorem module_finite_topologicalAbelianization {S : Set G} (hS : S.Finite)
    (hSN : (Subgroup.normalClosure S).topologicalClosure = N) :
    haveI : IsClosed (N : Set G) := hSN ▸ Subgroup.isClosed_topologicalClosure _
    letI := (hG.topologicalAbelianization N).completedGroupAlgebraModule (G ⧸ N)
    Module.Finite (completedGroupAlgebra ℤ_[p] (G ⧸ N))
      (Additive (TopologicalAbelianization N)) := by
  have : IsClosed (N : Set G) := hSN ▸ Subgroup.isClosed_topologicalClosure _
  -- The `(G ⧸ N)`-orbit of the classes of the elements of `S` generates a dense subgroup.
  have hgen := TopologicalAbelianization.topologicalClosure_closure_univ_smul_image_mk_eq_top hSN
  refine (hG.topologicalAbelianization N).module_finite_completedGroupAlgebraModule (G ⧸ N)
    (T := (QuotientGroup.mk : N → TopologicalAbelianization N) '' (Subtype.val ⁻¹' S))
    ((hS.preimage Subtype.val_injective.injOn).image _) ?_
  rw [dense_iff_closure_eq, ← Subgroup.topologicalClosure_coe, hgen, Subgroup.coe_top]

end NormalClosure

section Kernel

variable (hG : IsProP p G) (hfg : IsTopologicallyFinitelyGenerated G) {A : Type*} [CommGroup A]
  [TopologicalSpace A] [T1Space A] (χ : G →* A) (hχ : Continuous χ)
include hG hfg hχ

/-- **The kernel of a character of a topologically finitely generated pro-`p` group is the closed
normal closure of a finite set.** The kernel contains the closure of the commutator subgroup, which
is normally generated by the commutators of a finite topological generating set, and its image in
the abelianization is a closed subgroup of a topologically finitely generated abelian pro-`p`
group, hence topologically generated by finitely many elements, which lift to the kernel. -/
theorem exists_finite_topologicalClosure_normalClosure_eq_ker :
    ∃ S : Set G, S.Finite ∧ (Subgroup.normalClosure S).topologicalClosure = χ.ker := by
  have hker : IsClosed (χ.ker : Set G) := by
    rw [MonoidHom.coe_ker]
    exact isClosed_singleton.preimage hχ
  obtain ⟨s, hs⟩ := isTopologicallyFinitelyGenerated_iff.1 hfg
  -- The image of the kernel in the abelianization is topologically finitely generated.
  set q : G →* TopologicalAbelianization G := QuotientGroup.mk' _
  have hq : Continuous q := QuotientGroup.continuous_mk
  obtain ⟨t, ht, htK, hle⟩ := (hG.quotient _).exists_finite_subset_le_topologicalClosure_closure
    (hfg.quotient _) (Subgroup.isClosed_map hker.isCompact q hq)
  have hlift : ∀ y ∈ t, ∃ x, x ∈ χ.ker ∧ q x = y := fun y hy ↦ Subgroup.mem_map.1 (htK hy)
  choose! f hf using hlift
  refine ⟨Set.image2 (fun x y ↦ ⁅x, y⁆) (s : Set G) s ∪ f '' t,
    (s.finite_toSet.image2 _ s.finite_toSet).union (ht.image f), le_antisymm ?_ ?_⟩
  · -- Commutators and the lifted generators lie in the kernel.
    rw [Subgroup.topologicalClosure_normalClosure_le_iff hker]
    rintro x (⟨a, -, b, -, rfl⟩ | ⟨y, hy, rfl⟩)
    · rw [SetLike.mem_coe, MonoidHom.mem_ker, map_commutatorElement,
        commutatorElement_eq_one_iff_commute]
      exact Commute.all _ _
    · exact (hf y hy).1
  · set M := (Subgroup.normalClosure
      (Set.image2 (fun x y ↦ ⁅x, y⁆) (s : Set G) s ∪ f '' t)).topologicalClosure with hM_def
    have hcomm : (commutator G).topologicalClosure ≤ M :=
      Subgroup.topologicalClosure_commutator_le_of_forall_commutatorElement_mem hs
        (Subgroup.isClosed_topologicalClosure _) fun x hx y hy ↦
          Subgroup.le_topologicalClosure _
            (Subgroup.subset_normalClosure (Or.inl ⟨x, hx, y, hy, rfl⟩))
    -- The quotient map `G → G ⧸ M` factors through the abelianization.
    let φ : TopologicalAbelianization G →* G ⧸ M := QuotientGroup.lift _ (QuotientGroup.mk' M)
      fun x hx ↦ (QuotientGroup.eq_one_iff x).2 (hcomm hx)
    have hφq (x : G) : φ (q x) = (x : G ⧸ M) := QuotientGroup.lift_mk' _ _ x
    have hφ : Continuous φ := by
      refine (QuotientGroup.isQuotientMap_mk _).continuous_iff.2 ?_
      have : φ ∘ (QuotientGroup.mk : G → TopologicalAbelianization G) = QuotientGroup.mk :=
        funext hφq
      rw [this]
      exact QuotientGroup.continuous_mk
    intro x hx
    -- The image of `x` in `G^{ab}` lies in the closed subgroup generated by the images of `f '' t`.
    have ht' : (t : Set (TopologicalAbelianization G)) ⊆ q '' (f '' t) :=
      fun y hy ↦ ⟨f y, ⟨y, hy, rfl⟩, (hf y hy).2⟩
    have h1 : q x ∈ (Subgroup.closure (q '' (f '' t))).topologicalClosure :=
      Subgroup.topologicalClosure_mono (Subgroup.closure_mono ht')
        (hle (Subgroup.mem_map_of_mem q hx))
    -- Push forward along `φ`, which kills the images of `f '' t`.
    have h2 : φ (q x) ∈ (Subgroup.closure (φ '' (q '' (f '' t)))).topologicalClosure := by
      rw [← MonoidHom.map_closure]
      exact φ.map_topologicalClosure_le hφ _ (Subgroup.mem_map_of_mem φ h1)
    have h3 : φ '' (q '' (f '' t)) ⊆ {1} := by
      rintro _ ⟨_, ⟨_, ⟨y, hy, rfl⟩, rfl⟩, rfl⟩
      rw [Set.mem_singleton_iff, hφq, QuotientGroup.eq_one_iff]
      exact Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure (Or.inr ⟨y, hy, rfl⟩))
    have h4 : (⊥ : Subgroup (G ⧸ M)).topologicalClosure = ⊥ :=
      le_bot_iff.1 ((⊥ : Subgroup (G ⧸ M)).topologicalClosure_minimal le_rfl
        (by rw [Subgroup.coe_bot]; exact isClosed_singleton))
    rw [Subgroup.closure_eq_bot_iff.2 h3, h4, Subgroup.mem_bot, hφq,
      QuotientGroup.eq_one_iff] at h2
    exact h2

/-- **Labute's module is finitely generated.** For a continuous character `χ : G → A` of a
topologically finitely generated pro-`p` group `G` to a commutative `T1` group, the topological
abelianization `E = X ⧸ (X, X)` of `X = ker χ` is a finitely generated module over the completed
group algebra `Λ = ℤ_p[[G ⧸ X]]`, for the module structure
`TauCeti.IsProP.completedGroupAlgebraModule` through conjugation `ȳ • x̄ = [y x y⁻¹]`. For `G`
free pro-`p` of finite rank and `χ` an orientation `G → ℤ_pˣ` this is the module of Labute, §4,
on which the classification of Demushkin groups runs, with his action `ȳ · x̄ = [y⁻¹ x y]`
composed with the inversion of `Γ`; finite generation is the same statement for both conventions
(see the module docstring). The generators are the classes of the finite normal generating set
of `X` produced by `exists_finite_topologicalClosure_normalClosure_eq_ker`, not of prescribed
basis elements of `G`; the expression of the relator class in a normalized basis is a later step
of the classification. -/
theorem module_finite_topologicalAbelianization_ker :
    haveI : IsClosed (χ.ker : Set G) := χ.coe_ker ▸ isClosed_singleton.preimage hχ
    letI := (hG.topologicalAbelianization χ.ker).completedGroupAlgebraModule (G ⧸ χ.ker)
    Module.Finite (completedGroupAlgebra ℤ_[p] (G ⧸ χ.ker))
      (Additive (TopologicalAbelianization χ.ker)) := by
  obtain ⟨S, hS, hSker⟩ := hG.exists_finite_topologicalClosure_normalClosure_eq_ker hfg χ hχ
  exact hG.module_finite_topologicalAbelianization χ.ker hS hSker

end Kernel

end TauCeti.IsProP
