/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Padics.PrincipalUnits
import TauCeti.Topology.Algebra.Group.Subgroup

/-!
# The even part of a dyadic twisted subgroup

For `f ≥ 2`, the closed subgroup generated by a dyadic unit `u` whose negative `-u` has exact
principal-unit level `f` meets `1 + 4ℤ₂` in exactly `1 + 2 ^ (f + 1)ℤ₂`. The square of the
generator has principal-unit depth `f + 1`; its even and odd powers lie in two closed cosets,
and the odd coset is disjoint from `1 + 4ℤ₂`. The model case is `u = -1 + 2 ^ f`.
-/

public section

namespace TauCeti

/-- For `f ≥ 2` and a dyadic unit `u` with `-u` of exact level `f`, that is `-u ∈ U^(f)` but
`-u ∉ U^(f+1)`, the even part of the closed subgroup generated by `u` is `U^(f+1)`. The shift
by one comes from the exact principal-unit depth of `u²`. -/
theorem topologicalClosure_zpowers_inf_unitsPrincipal_two {f : ℕ} (hf : 2 ≤ f) {u : ℤ_[2]ˣ}
    (hneg : -u ∈ unitsPrincipal 2 f) (hneg' : -u ∉ unitsPrincipal 2 (f + 1)) :
    (Subgroup.zpowers u).topologicalClosure ⊓ unitsPrincipal 2 2 =
      unitsPrincipal 2 (f + 1) := by
  have hsq : (-u) ^ 2 = u ^ 2 := by
    apply Units.ext
    simp
  have hsqmem : u ^ 2 ∈ unitsPrincipal 2 (f + 1) := by
    simpa only [pow_one, hsq] using pow_pow_mem_unitsPrincipal (by omega) hneg 1
  have hsqnot : u ^ 2 ∉ unitsPrincipal 2 (f + 1 + 1) := by
    simpa only [pow_one, hsq] using
      pow_pow_notMem_unitsPrincipal (by omega) (fun _ ↦ hf) hneg hneg' 1
  have hclosure : (Subgroup.zpowers (u ^ 2)).topologicalClosure =
      unitsPrincipal 2 (f + 1) :=
    topologicalClosure_zpowers_eq_unitsPrincipal (by omega) (fun _ ↦ by omega) hsqmem hsqnot
  have hle : unitsPrincipal 2 (f + 1) ≤ unitsPrincipal 2 2 :=
    unitsPrincipal_antitone 2 (by omega)
  -- `u ∉ 1 + 4ℤ₂`, since otherwise `-1 = (-u) * u⁻¹ ∈ 1 + 4ℤ₂`
  have hunot : u ∉ unitsPrincipal 2 2 := by
    intro hmem
    have h := (unitsPrincipal 2 2).mul_mem (unitsPrincipal_antitone 2 hf hneg)
      ((unitsPrincipal 2 2).inv_mem hmem)
    rw [neg_mul, mul_inv_cancel, mem_unitsPrincipal_iff, Units.val_neg, Units.val_one,
      show (-1 : ℤ_[2]) - 1 = -(2 : ℤ_[2]) ^ 1 by norm_num, dvd_neg, Nat.cast_ofNat,
      pow_dvd_pow_iff (by norm_num : (2 : ℤ_[2]) ≠ 0) PadicInt.p_nonunit] at h
    omega
  refine le_antisymm ?_ (le_inf ?_ hle)
  · intro x hx
    rcases mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers u
      (unitsPrincipal 2 (f + 1)) (isClosed_unitsPrincipal 2 (f + 1)) hsqmem hx.1 with h | h
    · exact h
    · exact (hunot (by
        simpa using (unitsPrincipal 2 2).mul_mem hx.2
          ((unitsPrincipal 2 2).inv_mem (hle h)))).elim
  · rw [← hclosure]
    exact Subgroup.topologicalClosure_mono
      (Subgroup.zpowers_le.mpr (Subgroup.npow_mem_zpowers u 2))

/-- The model case `u = -1 + 2 ^ f` of `topologicalClosure_zpowers_inf_unitsPrincipal_two`:
here `-u = 1 - 2 ^ f` has exact level `f`. -/
theorem topologicalClosure_zpowers_inf_unitsPrincipal_two_of_val_eq {f : ℕ} (hf : 2 ≤ f)
    {u : ℤ_[2]ˣ} (hu : (u : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ f) :
    (Subgroup.zpowers u).topologicalClosure ⊓ unitsPrincipal 2 2 =
      unitsPrincipal 2 (f + 1) := by
  have hnegval : ((-u : ℤ_[2]ˣ) : ℤ_[2]) - 1 = -(2 : ℤ_[2]) ^ f := by
    rw [Units.val_neg, hu]
    ring
  refine topologicalClosure_zpowers_inf_unitsPrincipal_two hf ?_ ?_
  · rw [mem_unitsPrincipal_iff, hnegval]
    exact dvd_neg.mpr (dvd_refl _)
  · rw [mem_unitsPrincipal_iff, hnegval, dvd_neg, Nat.cast_ofNat,
      pow_dvd_pow_iff (by norm_num : (2 : ℤ_[2]) ≠ 0) PadicInt.p_nonunit]
    omega

end TauCeti
